# Keep all the dependencies up to date with a scheduled check
# See to https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
version: 2
updates:
  # Keep go modules up to date
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  # Keep github actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
