/*
This file is part of Cloud Native PostgreSQL.

Copyright (C) 2019-2021 EnterpriseDB Corporation.
*/

// Package constants provides the needed constants in the postgres package
package constants

const (
	// PostgresqlCustomConfigurationFile is the name of the file with the
	// PostgreSQL configuration parameters which is generated by the
	// operator
	PostgresqlCustomConfigurationFile = "custom.conf"

	// PostgresqlHBARulesFile is the name of the file which contains
	// the host-based access rules
	PostgresqlHBARulesFile = "pg_hba.conf"

	// PostgresqlIdentFile is the name of the file which contains
	// the user name maps
	PostgresqlIdentFile = "pg_ident.conf"

	// InitdbName is the name of the command to initialize a PostgreSQL database
	InitdbName = "initdb"
)
