linters-settings:
  lll:
    line-length: 120

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace

  # to be checked:
  # - errorlint
  # - forbidigo
  # - forcetypeassert
  # - goerr113
  # - ifshort
  # - nilerr
  # - nlreturn
  # - noctx
  # - nolintlint
  # - paralleltest
  # - promlinter
  # - tagliatelle
  # - wrapcheck

  # don't enable:
  # - cyclop
  # - exhaustive
  # - exhaustivestruct
  # - funlen
  # - gci
  # - gochecknoglobals
  # - gochecknoinits
  # - godot
  # - godox
  # - gomnd
  # - testpackage
  # - wsl

  # deprecated:
  # - golint
  # - interfacer
  # - maligned
  # - scopelint

run:
  skip-files: "zz_generated.*"

issues:
  exclude-rules:
    # Exclude lll issues for lines with long annotations
    - linters:
      - lll
      source: "//\\s*\\+"
    # We have no control of this in zz_generated files and it looks like that excluding those files is not enough
    # so we disable "ST1016: methods on the same type should have the same receiver name" in api directory
    - linters:
      - stylecheck
      text: "ST1016:"
      path: api/
    - linters:
      - dupl
      path: api/v1alpha1/.*_webhook\.go
  exclude-use-default: false
