version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - ginkgolinter
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    gosec:
      excludes:
        - G101
    staticcheck:
      checks:
        - all
        - '-QF1001'
        - '-QF1007'
    lll:
      line-length: 120
    importas:
      alias:
        - pkg: github.com/cloudnative-pg/cloudnative-pg/api/v1
          alias: apiv1
        - pkg: github.com/cloudnative-pg/cloudnative-pg/internal/webhook/v1
          alias: webhookv1
        - pkg: github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1
          alias: volumesnapshotv1
        - pkg: github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1
          alias: monitoringv1
        - pkg: k8s.io/api/admissionregistration/v1
          alias: admissionregistrationv1
        - pkg: k8s.io/api/apps/v1
          alias: appsv1
        - pkg: k8s.io/api/batch/v1
          alias: batchv1
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/api/discovery/v1
          alias: discoveryv1
        - pkg: k8s.io/api/events/v1
          alias: eventsv1
        - pkg: k8s.io/api/policy/v1
          alias: policyv1
        - pkg: k8s.io/api/rbac/v1
          alias: rbacv1
        - pkg: k8s.io/api/storage/v1
          alias: storagev1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/client-go/kubernetes/typed/core/v1
          alias: corev1client
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: should not use dot imports
        source: ginkgo|gomega
      - linters:
          - goconst
        path: _test\.go
      - linters:
          - lll
        source: //\s*\+
      - linters:
          - staticcheck
        path: api/
        text: 'ST1016:'
      - linters:
          - revive
        path: /(utils|common)/[^/]+.go
        text: avoid meaningless package names
    paths:
      - zz_generated.*
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cloudnative-pg/cloudnative-pg)
        - blank
        - dot
  exclusions:
    generated: lax
    paths:
      - zz_generated.*
      - third_party$
      - builtin$
      - examples$
