project_name: cnpg

release:
  github:
    owner: cloudnative-pg
    name: cloudnative-pg

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
- id: manager
  binary: manager
  main: cmd/manager/main.go
  gcflags:
    - all=-trimpath={{.Env.GOPATH}};{{.Env.PWD}}
  ldflags:
    - -s
    - -w
    - -X github.com/cloudnative-pg/cloudnative-pg/pkg/versions.buildVersion={{.Env.VERSION}}
    - -X github.com/cloudnative-pg/cloudnative-pg/pkg/versions.buildCommit={{.Env.COMMIT}}
    - -X github.com/cloudnative-pg/cloudnative-pg/pkg/versions.buildDate={{.Env.DATE}}
  goos:
    - linux
  goarch:
    - amd64

- id: kubectl-cnpg
  binary: kubectl-cnpg
  main: cmd/kubectl-cnpg/main.go
  gcflags:
  - all=-trimpath={{.Env.GOPATH}};{{.Env.PWD}}
  ldflags:
  - -s
  - -w
  - -X github.com/cloudnative-pg/cloudnative-pg/pkg/versions.buildVersion={{.Env.VERSION}}
  - -X github.com/cloudnative-pg/cloudnative-pg/pkg/versions.buildCommit={{.Env.COMMIT}}
  - -X github.com/cloudnative-pg/cloudnative-pg/pkg/versions.buildDate={{.Env.DATE}}
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - 386
  - arm64
  - arm
  - ppc64le
  - s390x
  goarm:
  - 5
  - 6
  - 7
  ignore:
  - goos: darwin
    goarch: 386
  - goos: windows
    goarch: ppc64le
  - goos: windows
    goarch: s390x

archives:
- name_template: kubectl-cnpg_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}
  builds:
  - kubectl-cnpg
  replacements:
    386: i386
    amd64: x86_64

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

krews:
  - name: cnpg
    homepage: https://github.com/cloudnative-pg/cloudnative-pg
    short_description: 'Manage your CloudNativePG clusters'
    skip_upload: true
    description: 'This plugin provides multiple commands to help you manage your CloudNativePG clusters.'
