
# Default internal rules refer https://github.com/get-woke/woke/blob/main/internal/rule/default.yaml
rules:
  - name: master
    terms:
      - master
    alternatives:
      - leader
      - primary
    options:
      word_boundary: true
