FROM registry.access.redhat.com/ubi9/ubi-micro
ARG VERSION="dev"
ARG TARGETARCH

ENV SUMMARY="CloudNativePG Operator Container Image." \
    DESCRIPTION="This Docker image contains CloudNativePG Operator." \
    MAINTAINER="CloudNativePG Contributors."

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.display-name="$SUMMARY" \
      io.k8s.description="$DESCRIPTION" \
      name="CloudNativePG Operator" \
      vendor="$MAINTAINER" \
      maintainer="$MAINTAINER" \
      url="https://cloudnative-pg.io/" \
      version="$VERSION" \
      release="1"

COPY licenses /licenses
COPY LICENSE /licenses

WORKDIR /

COPY dist/manager/* /bin/
RUN ln -sf /bin/manager_${TARGETARCH} manager
USER 65532:65532

ENTRYPOINT ["/manager"]
