---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - postgresql.cnpg.io
  resources:
    - clusterimagecatalogs
  verbs:
    - get
    - list
    - watch
