/*
Copyright © contributors to CloudNativePG, established as
CloudNativePG a Series of LF Projects, LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package e2e

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/onsi/ginkgo/v2/types"
	"github.com/thoas/go-funk"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	k8sscheme "k8s.io/client-go/kubernetes/scheme"

	// +kubebuilder:scaffold:imports
	apiv1 "github.com/cloudnative-pg/cloudnative-pg/api/v1"
	cnpgUtils "github.com/cloudnative-pg/cloudnative-pg/pkg/utils"
	"github.com/cloudnative-pg/cloudnative-pg/pkg/versions"
	"github.com/cloudnative-pg/cloudnative-pg/tests"
	"github.com/cloudnative-pg/cloudnative-pg/tests/config"
	"github.com/cloudnative-pg/cloudnative-pg/tests/utils/cloudvendors"
	"github.com/cloudnative-pg/cloudnative-pg/tests/utils/environment"
	"github.com/cloudnative-pg/cloudnative-pg/tests/utils/namespaces"
	"github.com/cloudnative-pg/cloudnative-pg/tests/utils/objects"
	"github.com/cloudnative-pg/cloudnative-pg/tests/utils/objectstore"
	"github.com/cloudnative-pg/cloudnative-pg/tests/utils/operator"
	"github.com/cloudnative-pg/cloudnative-pg/tests/utils/sternmultitailer"
	"github.com/cloudnative-pg/cloudnative-pg/tests/utils/timeouts"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

const (
	fixturesDir  = "./fixtures"
	RetryTimeout = environment.RetryTimeout
	PollingTime  = objects.PollingTime
)

var (
	env                     *environment.TestingEnvironment
	testLevelEnv            *tests.TestEnvLevel
	testCloudVendorEnv      *cloudvendors.TestEnvVendor
	expectedOperatorPodName string
	operatorPodWasRenamed   bool
	operatorWasRestarted    bool
	quickDeletionPeriod     = int64(1)
	testTimeouts            map[timeouts.Timeout]int
	objectStoreEnv          = &objectstore.Env{
		Namespace:    "object-store",
		ServiceName:  "object-store.object-store",
		CaSecretName: "object-store-ca-secret",
		TLSSecret:    "object-store-tls-secret",
	}

	// e2eConfigPath points to the configuration file driving the run,
	// usually generated by the hack/e2e scripts
	e2eConfigPath = flag.String("e2e-config", config.DefaultPath,
		"path of the e2e configuration file")
)

var _ = SynchronizedBeforeSuite(func() []byte {
	var err error
	env, err = environment.NewTestingEnvironment()
	Expect(err).ShouldNot(HaveOccurred())

	display := func(s string) string {
		if strings.TrimSpace(s) == "" {
			return "<none>"
		}
		return s
	}
	cfg := config.Current()
	_, _ = fmt.Fprintf(
		GinkgoWriter, `
E2E test configuration:
  Operator version:              %s
  Postgres image:                %s:%s
  Postgres version:              %d
  Postgres image repository:     %s
  PostGIS image repository:      %s
  Pre-rolling update image:      %s
  Cloud vendor:                  %s
  Default storage class:         %s
  CSI storage class:             %s
  Default volume snapshot class: %s
  CNPG deployment method:        %s
  Barman plugin selector:        %s
  Barman plugin version:         %s
`,
		versions.Version,
		env.PostgresImageName, env.PostgresImageTag,
		env.PostgresVersion,
		display(cfg.Postgres.ImageRepository),
		display(cfg.Postgres.PostGISImageRepository),
		display(cfg.Postgres.PreRollingUpdateImage),
		display(cfg.CloudVendor),
		display(env.DefaultStorageClass),
		display(env.CSIStorageClass),
		display(env.DefaultVolumeSnapshotClass),
		display(cfg.Deployment.Method),
		display(cfg.Deployment.BarmanPluginVersion),
		display(cfg.Deployment.BarmanPluginVersionResolved),
	)

	// Start stern to write the logs of every pod we are interested in. Since we don't have a way to have a selector
	// matching both the operator's and the clusters' pods, we need to start stern twice.
	sternClustersCtx, sternClusterCancel := context.WithCancel(env.Ctx)
	sternClusterDoneChan := sternmultitailer.StreamLogs(sternClustersCtx, env.Interface, clusterPodsLabelSelector(),
		namespaces.SternLogDirectory)
	DeferCleanup(func() {
		sternClusterCancel()
		<-sternClusterDoneChan
	})
	sternOperatorCtx, sternOperatorCancel := context.WithCancel(env.Ctx)
	sternOperatorDoneChan := sternmultitailer.StreamLogs(sternOperatorCtx, env.Interface, operatorPodsLabelSelector(),
		namespaces.SternLogDirectory)
	DeferCleanup(func() {
		sternOperatorCancel()
		<-sternOperatorDoneChan
	})

	_ = corev1.AddToScheme(env.Scheme)
	_ = appsv1.AddToScheme(env.Scheme)

	// Set up a global object storage service in its own namespace
	err = namespaces.CreateNamespace(env.Ctx, env.Client, objectStoreEnv.Namespace)
	Expect(err).ToNot(HaveOccurred())
	DeferCleanup(func() {
		err := namespaces.DeleteNamespaceAndWait(env.Ctx, env.Client, objectStoreEnv.Namespace, 300)
		Expect(err).ToNot(HaveOccurred())
	})
	objectStoreEnv.Timeout = uint(testTimeouts[timeouts.ObjectStoreInstallation])
	objectStoreClient, err := objectstore.Deploy(objectStoreEnv, env)
	Expect(err).ToNot(HaveOccurred())

	caSecret := objectStoreEnv.CaPair.GenerateCASecret(objectStoreEnv.Namespace, objectStoreEnv.CaSecretName)
	objectStoreEnv.CaSecretObj = *caSecret
	objs := map[string]appsv1.Deployment{
		"object-store": *objectStoreClient,
	}

	jsonObjs, err := json.Marshal(objs)
	if err != nil {
		panic(err)
	}

	return jsonObjs
}, func(jsonObjs []byte) {
	var err error
	// We are creating new testing env object again because above testing env can not serialize and
	// accessible to all nodes (specs)
	if env, err = environment.NewTestingEnvironment(); err != nil {
		panic(err)
	}

	_ = k8sscheme.AddToScheme(env.Scheme)
	_ = apiv1.AddToScheme(env.Scheme)

	if testLevelEnv, err = tests.TestLevel(); err != nil {
		panic(err)
	}

	if testTimeouts, err = timeouts.Timeouts(); err != nil {
		panic(err)
	}

	if testCloudVendorEnv, err = cloudvendors.TestCloudVendor(); err != nil {
		panic(err)
	}

	var objs map[string]*appsv1.Deployment
	if err := json.Unmarshal(jsonObjs, &objs); err != nil {
		panic(err)
	}

	objectStoreEnv.Client = objs["object-store"]
})

var _ = BeforeEach(func() {
	labelsForTestsBreakingTheOperator := []string{"upgrade", "disruptive"}
	breakingLabelsInCurrentTest := funk.Join(CurrentSpecReport().Labels(),
		labelsForTestsBreakingTheOperator, funk.InnerJoin)

	if len(breakingLabelsInCurrentTest.([]string)) != 0 {
		return
	}

	operatorPod, err := operator.GetPod(env.Ctx, env.Client)
	Expect(err).ToNot(HaveOccurred())

	if operatorPodWasRenamed {
		Skip("Skipping test. Operator was renamed")
	}
	if operatorWasRestarted {
		Skip("Skipping test. Operator was restarted")
	}

	expectedOperatorPodName = operatorPod.GetName()
})

func TestE2ESuite(t *testing.T) {
	RegisterFailHandler(Fail)
	SetDefaultEventuallyPollingInterval(1 * time.Second)

	cfg, err := config.Load(*e2eConfigPath)
	if err != nil {
		// Running without a configuration file is supported: it is
		// equivalent to an empty one. An explicitly passed path, instead,
		// must exist.
		if !errors.Is(err, os.ErrNotExist) || *e2eConfigPath != config.DefaultPath {
			t.Fatalf("could not load the e2e configuration: %v", err)
		}
		cfg = config.NewDefault()
	}
	config.Set(cfg)

	suiteConfig, reporterConfig := GinkgoConfiguration()
	if cfg.LabelFilter != "" {
		suiteConfig.LabelFilter = cfg.LabelFilter
	}

	RunSpecs(t, "CloudNativePG Operator E2E", suiteConfig, reporterConfig)
}

// Before the end of the tests we should verify that the operator never restarted
// and that the operator pod name didn't change.
// If either of those things happened, the test will fail, and all subsequent
// tests will be SKIPPED, as they would always fail in this node.
var _ = AfterEach(func() {
	if CurrentSpecReport().State.Is(types.SpecStateSkipped) {
		return
	}
	labelsForTestsBreakingTheOperator := []string{"upgrade", "disruptive"}
	breakingLabelsInCurrentTest := funk.Join(CurrentSpecReport().Labels(),
		labelsForTestsBreakingTheOperator, funk.InnerJoin)
	if len(breakingLabelsInCurrentTest.([]string)) != 0 {
		return
	}
	operatorPod, err := operator.GetPod(env.Ctx, env.Client)
	Expect(err).ToNot(HaveOccurred())
	wasRenamed := operator.PodRenamed(operatorPod, expectedOperatorPodName)
	if wasRenamed {
		operatorPodWasRenamed = true
		Fail("operator was renamed")
	}
	wasRestarted := operator.PodRestarted(operatorPod)
	if wasRestarted {
		operatorWasRestarted = true
		Fail("operator was restarted")
	}
})

// clusterPodsLabelSelector returns a label selector to match all the pods belonging to the CNPG clusters
func clusterPodsLabelSelector() labels.Selector {
	labelSelector, _ := metav1.LabelSelectorAsSelector(&metav1.LabelSelector{
		MatchExpressions: []metav1.LabelSelectorRequirement{
			{
				Key:      cnpgUtils.ClusterLabelName,
				Operator: metav1.LabelSelectorOpExists,
			},
		},
	})
	return labelSelector
}

// operatorPodsLabelSelector returns a label selector to match all the pods belonging to the CNPG operator
func operatorPodsLabelSelector() labels.Selector {
	labelSelector, _ := metav1.LabelSelectorAsSelector(&metav1.LabelSelector{
		MatchLabels: map[string]string{
			"app.kubernetes.io/name": "cloudnative-pg",
		},
	})
	return labelSelector
}
