/*
Copyright © contributors to CloudNativePG, established as
CloudNativePG a Series of LF Projects, LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package controller

import (
	"context"
	"fmt"
	"reflect"

	"github.com/cloudnative-pg/machinery/pkg/log"
	corev1 "k8s.io/api/core/v1"
	apierrs "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	apiv1 "github.com/cloudnative-pg/cloudnative-pg/api/v1"
	"github.com/cloudnative-pg/cloudnative-pg/pkg/specs"
	"github.com/cloudnative-pg/cloudnative-pg/pkg/utils"
)

// passwordDependentSecretKeys are the keys generated by specs.CreateSecret that
// only make sense when a password is available. They are removed from the
// connection Secret when the owner's password cannot be resolved.
var passwordDependentSecretKeys = []string{
	"password",
	"pgpass",
	"uri",
	"jdbc-uri",
	"fqdn-uri",
	"fqdn-jdbc-uri",
}

// DatabaseSecretReconciler reconciles the connection Secret generated for a
// declaratively-created Database object.
//
// This controller runs in the operator (not in the instance manager). The
// instance manager intentionally lacks the RBAC to create or update arbitrary
// Secrets, so Secret generation must happen here, where the operator already
// holds the required permissions. This mirrors the operator-side
// DatabaseRoleReconciler, which generates the client-certificate Secret.
type DatabaseSecretReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=postgresql.cnpg.io,resources=databases,verbs=get;list;watch
// +kubebuilder:rbac:groups=postgresql.cnpg.io,resources=databaseroles,verbs=get;list;watch
// +kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch;create;update;patch;delete

// Reconcile generates (or refreshes) the connection Secret for a Database.
func (r *DatabaseSecretReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	contextLogger, ctx := log.SetupLogger(ctx)

	var database apiv1.Database
	if err := r.Get(ctx, req.NamespacedName, &database); err != nil {
		if apierrs.IsNotFound(err) {
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, fmt.Errorf("cannot get the database resource: %w", err)
	}

	// The connection Secret is owned by the Database and is therefore garbage
	// collected automatically when the Database is deleted; nothing to do here.
	if !database.DeletionTimestamp.IsZero() {
		return ctrl.Result{}, nil
	}

	if err := r.reconcileConnectionSecret(ctx, &database); err != nil {
		contextLogger.Error(err, "while reconciling the database connection secret")
		return ctrl.Result{}, err
	}

	return ctrl.Result{}, nil
}

// reconcileConnectionSecret builds the connection Secret for the Database,
// reusing the exact format produced by specs.CreateSecret for the application
// user Secret, and creates or patches it.
func (r *DatabaseSecretReconciler) reconcileConnectionSecret(
	ctx context.Context,
	database *apiv1.Database,
) error {
	// Resolving the owner's password is best-effort: a missing DatabaseRole or
	// password Secret must not fail reconciliation. In that case we still
	// publish a connection Secret, omitting the password-dependent fields.
	pwd, err := r.resolveOwnerPassword(ctx, database)
	if err != nil {
		return err
	}

	// The read-write service name can be derived from the cluster reference
	// without fetching the Cluster object, matching cluster.GetServiceReadWriteName().
	hostname := database.Spec.ClusterRef.Name + apiv1.ServiceReadWriteSuffix

	secret := specs.CreateSecret(
		database.GetConnectionSecretName(),
		database.Namespace,
		hostname,
		database.Spec.Name,
		database.Spec.Owner,
		pwd,
		utils.UserTypeApp,
	)

	if pwd == "" {
		for _, key := range passwordDependentSecretKeys {
			delete(secret.StringData, key)
		}
	}

	if err := ctrl.SetControllerReference(database, secret, r.Scheme); err != nil {
		return fmt.Errorf("while setting owner reference on connection secret %q: %w", secret.Name, err)
	}

	return r.createOrPatchConnectionSecret(ctx, database, secret)
}

// resolveOwnerPassword looks up the DatabaseRole that owns the Database and
// returns the password stored in its referenced Secret. It returns an empty
// string (and no error) whenever the role or the password cannot be resolved,
// so that reconciliation can continue and still publish a connection Secret.
func (r *DatabaseSecretReconciler) resolveOwnerPassword(
	ctx context.Context,
	database *apiv1.Database,
) (string, error) {
	contextLogger := log.FromContext(ctx)

	var roles apiv1.DatabaseRoleList
	if err := r.List(ctx, &roles, client.InNamespace(database.Namespace)); err != nil {
		return "", fmt.Errorf("while listing database roles: %w", err)
	}

	role := findOwnerRole(roles, database)
	if role == nil {
		contextLogger.Debug(
			"no DatabaseRole found for the database owner, "+
				"generating connection secret without password",
			"owner", database.Spec.Owner,
		)
		return "", nil
	}

	if role.Spec.PasswordSecret == nil {
		contextLogger.Debug(
			"the DatabaseRole owning the database has no password secret, "+
				"generating connection secret without password",
			"role", role.Name,
		)
		return "", nil
	}

	var passwordSecret corev1.Secret
	if err := r.Get(ctx, types.NamespacedName{
		Namespace: database.Namespace,
		Name:      role.Spec.PasswordSecret.Name,
	}, &passwordSecret); err != nil {
		if apierrs.IsNotFound(err) {
			contextLogger.Info(
				"password secret referenced by the DatabaseRole not found, "+
					"generating connection secret without password",
				"role", role.Name,
				"passwordSecret", role.Spec.PasswordSecret.Name,
			)
			return "", nil
		}
		return "", fmt.Errorf("while getting password secret %q: %w", role.Spec.PasswordSecret.Name, err)
	}

	return string(passwordSecret.Data[corev1.BasicAuthPasswordKey]), nil
}

// createOrPatchConnectionSecret creates the connection Secret if it does not
// exist, or patches it when it is owned by the Database and out of date.
// Secrets with the same name that are not owned by the Database are left
// untouched.
func (r *DatabaseSecretReconciler) createOrPatchConnectionSecret(
	ctx context.Context,
	database *apiv1.Database,
	proposed *corev1.Secret,
) error {
	contextLogger := log.FromContext(ctx)

	// StringData is write-only and never returned by the API server: convert it
	// to Data so the existing Secret can be compared and patched reliably.
	proposed.Data = map[string][]byte{}
	for key, value := range proposed.StringData {
		proposed.Data[key] = []byte(value)
	}
	proposed.StringData = nil

	var currentSecret corev1.Secret
	if err := r.Get(ctx, client.ObjectKey{
		Namespace: proposed.Namespace,
		Name:      proposed.Name,
	}, &currentSecret); apierrs.IsNotFound(err) {
		return r.Create(ctx, proposed)
	} else if err != nil {
		return fmt.Errorf("while getting connection secret %q: %w", proposed.Name, err)
	}

	// Never modify a same-named Secret the operator does not own: it may belong
	// to the user or another component.
	if !metav1.IsControlledBy(&currentSecret, database) {
		contextLogger.Warning(
			"connection secret already exists and is not owned by this Database, skipping",
			"secret", proposed.Name,
		)
		return nil
	}

	patchedSecret := currentSecret.DeepCopy()
	utils.MergeObjectsMetadata(patchedSecret, proposed)
	patchedSecret.Data = proposed.Data

	if reflect.DeepEqual(patchedSecret.Labels, currentSecret.Labels) &&
		reflect.DeepEqual(patchedSecret.Annotations, currentSecret.Annotations) &&
		reflect.DeepEqual(patchedSecret.Data, currentSecret.Data) {
		return nil
	}

	return r.Patch(ctx, patchedSecret, client.MergeFrom(&currentSecret))
}

// SetupWithManager registers the controller with the manager and wires the
// watches that trigger a reconciliation when the owner role or its password
// Secret change.
func (r *DatabaseSecretReconciler) SetupWithManager(mgr ctrl.Manager, maxConcurrentReconciles int) error {
	return ctrl.NewControllerManagedBy(mgr).
		WithOptions(controller.Options{MaxConcurrentReconciles: maxConcurrentReconciles}).
		For(&apiv1.Database{}).
		Named("database-secret").
		// Connection Secrets owned by a Database: re-enqueue the owner on any
		// change so an externally deleted or modified Secret is regenerated.
		Owns(&corev1.Secret{}).
		// DatabaseRole: a change to the role that owns a Database (e.g. its
		// password secret reference) must refresh the connection Secret.
		Watches(
			&apiv1.DatabaseRole{},
			handler.EnqueueRequestsFromMapFunc(r.mapRoleToDatabases()),
		).
		// Password Secrets referenced by an owner DatabaseRole: a password
		// rotation must be propagated to the connection Secret.
		Watches(
			&corev1.Secret{},
			handler.EnqueueRequestsFromMapFunc(r.mapPasswordSecretToDatabases()),
		).
		Complete(r)
}

// mapRoleToDatabases enqueues every Database owned by the changed DatabaseRole.
func (r *DatabaseSecretReconciler) mapRoleToDatabases() handler.MapFunc {
	return func(ctx context.Context, obj client.Object) []reconcile.Request {
		role, ok := obj.(*apiv1.DatabaseRole)
		if !ok {
			return nil
		}

		var databases apiv1.DatabaseList
		if err := r.List(ctx, &databases, client.InNamespace(role.Namespace)); err != nil {
			log.FromContext(ctx).Error(err, "while listing databases for role", "role", role.Name)
			return nil
		}

		var result []reconcile.Request
		for i := range databases.Items {
			db := &databases.Items[i]
			if db.Spec.Owner == role.Spec.Name && db.Spec.ClusterRef.Name == role.Spec.ClusterRef.Name {
				result = append(result, reconcile.Request{
					NamespacedName: types.NamespacedName{Name: db.Name, Namespace: db.Namespace},
				})
			}
		}
		return result
	}
}

// mapPasswordSecretToDatabases enqueues every Database whose owner role uses the
// changed Secret as its password Secret.
func (r *DatabaseSecretReconciler) mapPasswordSecretToDatabases() handler.MapFunc {
	return func(ctx context.Context, obj client.Object) []reconcile.Request {
		secret, ok := obj.(*corev1.Secret)
		if !ok {
			return nil
		}

		var roles apiv1.DatabaseRoleList
		if err := r.List(ctx, &roles, client.InNamespace(secret.Namespace)); err != nil {
			log.FromContext(ctx).Error(err, "while listing roles for secret", "secret", secret.Name)
			return nil
		}

		var databases apiv1.DatabaseList
		if err := r.List(ctx, &databases, client.InNamespace(secret.Namespace)); err != nil {
			log.FromContext(ctx).Error(err, "while listing databases for secret", "secret", secret.Name)
			return nil
		}

		var result []reconcile.Request
		for i := range roles.Items {
			role := &roles.Items[i]
			if role.Spec.PasswordSecret == nil || role.Spec.PasswordSecret.Name != secret.Name {
				continue
			}
			for j := range databases.Items {
				db := &databases.Items[j]
				if db.Spec.Owner == role.Spec.Name && db.Spec.ClusterRef.Name == role.Spec.ClusterRef.Name {
					result = append(result, reconcile.Request{
						NamespacedName: types.NamespacedName{Name: db.Name, Namespace: db.Namespace},
					})
				}
			}
		}
		return result
	}
}

// findOwnerRole returns the DatabaseRole that owns the Database, matched by the
// role name and the cluster it belongs to.
func findOwnerRole(roles apiv1.DatabaseRoleList, database *apiv1.Database) *apiv1.DatabaseRole {
	for i := range roles.Items {
		role := &roles.Items[i]
		if role.Spec.Name == database.Spec.Owner &&
			role.Spec.ClusterRef.Name == database.Spec.ClusterRef.Name {
			return role
		}
	}
	return nil
}
