/*
Copyright © contributors to CloudNativePG, established as
CloudNativePG a Series of LF Projects, LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package controller

import (
	"context"
	"fmt"
	"reflect"
	"time"

	"github.com/cloudnative-pg/machinery/pkg/log"
	corev1 "k8s.io/api/core/v1"
	apierrs "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/builder"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	apiv1 "github.com/cloudnative-pg/cloudnative-pg/api/v1"
	"github.com/cloudnative-pg/cloudnative-pg/pkg/certs"
)

// DatabaseRoleReconciler reconciles a DatabaseRole object
type DatabaseRoleReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

// roleSecretReconcileInterval is the requeue period for roles whose client
// certificate or password is generated by the operator, ensuring both are
// renewed before expiry even in the absence of a triggering event.
const roleSecretReconcileInterval = time.Hour

// +kubebuilder:rbac:groups=postgresql.cnpg.io,resources=databaseroles,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=postgresql.cnpg.io,resources=databaseroles/status,verbs=get;update;patch;watch
// +kubebuilder:rbac:groups=postgresql.cnpg.io,resources=databaseroles/finalizers,verbs=update
// +kubebuilder:rbac:groups=postgresql.cnpg.io,resources=clusters,verbs=get;list;watch
// +kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch;create;update;patch;delete

// Reconcile implements the main reconciliation loop for Role objects
func (r *DatabaseRoleReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	contextLogger, ctx := log.SetupLogger(ctx)

	var role apiv1.DatabaseRole
	if err := r.Get(ctx, req.NamespacedName, &role); err != nil {
		if apierrs.IsNotFound(err) {
			contextLogger.Info("Resource has been deleted")
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, fmt.Errorf("cannot get the role resource: %w", err)
	}

	// A deleted role is waiting for the instance manager to resolve its
	// finalizer: generating a secret for it is pointless, and rotating the
	// password of a role that is about to be retained would leave it with a
	// credential nobody ever got to read.
	if !role.DeletionTimestamp.IsZero() {
		return ctrl.Result{}, nil
	}

	origRole := role.DeepCopy()

	// Both the password and the client certificate are generated out of the
	// cluster the role belongs to, and neither is generated while it is missing.
	cluster, err := r.getReferencedCluster(ctx, &role)
	if err != nil {
		return ctrl.Result{}, err
	}

	// The password Secret is reconciled before the condition that tracks it, so
	// that a freshly generated password is picked up by the instance manager in
	// this same loop.
	if err := r.reconcilePassword(ctx, &role, cluster); err != nil {
		return ctrl.Result{}, err
	}

	if err := r.reconcilePasswordCondition(ctx, &role); err != nil {
		return ctrl.Result{}, err
	}

	// A failure here must not cost us the status of the password: the
	// PasswordSecretChange condition is how the instance manager learns that a
	// password has just been rotated, and dropping it would leave the new
	// password in its Secret and never applied to PostgreSQL.
	certErr := r.reconcileClientCertificate(ctx, &role, cluster)

	// A manual password rotation request is consumed by removing the
	// annotation that asked for it once reconcilePassword has acted on it.
	// Patch that separately from the status, which the instance manager also
	// writes to and which this Patch (on the main resource, not the /status
	// subresource) does not touch. The patch is applied to a copy: the API
	// server answers with the stored object, whose status does not carry the
	// changes still only held in memory here, and unmarshalling that over
	// `role` would lose them before they are persisted below.
	if !reflect.DeepEqual(origRole.Annotations, role.Annotations) {
		annotated := role.DeepCopy()
		if err := r.Patch(ctx, annotated, client.MergeFrom(origRole)); err != nil {
			return ctrl.Result{}, fmt.Errorf("while patching role annotations: %w", err)
		}
	}

	// A DatabaseRole has two status writers: the instance manager owns every
	// field except the PasswordSecretChange condition, the Password state and
	// the ClientCertificate state, all set here. Merge-patch so we only touch
	// our own fields and never clobber the instance manager's update.
	if !reflect.DeepEqual(origRole.Status, role.Status) {
		if err := r.Status().Patch(ctx, &role, client.MergeFrom(origRole)); err != nil {
			return ctrl.Result{}, fmt.Errorf("while patching role status: %w", err)
		}
	}

	if certErr != nil {
		return ctrl.Result{}, certErr
	}

	if next := nextRoleSecretReconcile(&role); next > 0 {
		return ctrl.Result{RequeueAfter: next}, nil
	}
	return ctrl.Result{}, nil
}

// nextRoleSecretReconcile returns how long from now the role's client
// certificate or password should next be checked for renewal, or zero when
// neither is enabled. The certificate falls back to the fixed
// roleSecretReconcileInterval; the password instead requeues right at its
// renewal deadline, since duration/renewBefore can be far shorter than that
// interval, and a flat hourly check would leave a short-lived password
// overdue for most of its remaining life.
func nextRoleSecretReconcile(role *apiv1.DatabaseRole) time.Duration {
	var next time.Duration
	certEnabled := role.IsClientCertificateEnabled()
	if certEnabled {
		next = roleSecretReconcileInterval
	}

	if role.IsPasswordRotationEnabled() {
		untilRenewal := untilPasswordRenewal(role)
		if !certEnabled || untilRenewal < next {
			next = untilRenewal
		}
	}

	return next
}

// untilPasswordRenewal returns how long from now the password of the role is
// due for renewal, falling back to the fixed roleSecretReconcileInterval when
// its recorded expiration cannot be read, and flooring at one second when the
// deadline has already passed, since a zero or negative RequeueAfter would
// mean no further requeue at all rather than a prompt retry.
func untilPasswordRenewal(role *apiv1.DatabaseRole) time.Duration {
	if role.Status.Password == nil || role.Status.Password.Expiration == "" {
		return roleSecretReconcileInterval
	}

	expiration, err := time.Parse(time.RFC3339, role.Status.Password.Expiration)
	if err != nil {
		return roleSecretReconcileInterval
	}

	// A rotation this reconciliation just performed already moved the
	// deadline forward; anything else means the password could not be
	// rotated (an unowned Secret, an unsatisfiable criteria).
	renewalDue := expiration.Add(-passwordRenewBefore(role))
	if untilRenewal := time.Until(renewalDue); untilRenewal > 0 {
		return untilRenewal
	}
	return time.Second
}

// reconcilePasswordCondition manages the ConditionPasswordSecretChange status condition.
// If the role has no password secret, the condition is removed. If the secret is found,
// the condition is set with the secret's ResourceVersion so the instance manager can
// detect when the password changed. The condition is only updated in memory: the caller
// persists it together with the rest of the status the operator owns.
func (r *DatabaseRoleReconciler) reconcilePasswordCondition(
	ctx context.Context,
	role *apiv1.DatabaseRole,
) error {
	secretName := role.GetPasswordSecretName()
	if secretName == "" {
		// If the password secret was removed, clear any stale PasswordSecretChange
		// condition left over from a previously configured secret.
		meta.RemoveStatusCondition(&role.Status.Conditions, string(apiv1.ConditionPasswordSecretChange))
		return nil
	}

	var secret corev1.Secret
	if err := r.Get(ctx, types.NamespacedName{
		Namespace: role.Namespace,
		Name:      secretName,
	}, &secret); err != nil {
		// There's no need to fill the operator log with errors
		// if the secret still doesn't exist.
		if apierrs.IsNotFound(err) {
			return nil
		}

		return fmt.Errorf(
			"while getting secret %q referred by role %q: %w",
			secretName,
			role.Name,
			err,
		)
	}

	// The instance manager, which runs the controller that applies the Role spec
	// to the PostgreSQL database, cannot watch Secrets directly. Granting that
	// permission would allow it to watch all Secrets in the namespace, which is
	// undesirable from a security standpoint. Unfortunately, the Kubernetes API
	// does not support watching a specific subset of Secrets.
	//
	// To work around this, the operator (which has the necessary permissions)
	// watches Secrets and detects changes to those referenced by Role objects.
	// When a change is detected, the operator updates a condition on the Role,
	// storing the Secret's ResourceVersion. This status update triggers a
	// reconciliation cycle in the instance manager, which then reads the updated
	// password and applies it to PostgreSQL.
	meta.SetStatusCondition(&role.Status.Conditions, metav1.Condition{
		Type:    string(apiv1.ConditionPasswordSecretChange),
		Status:  metav1.ConditionTrue,
		Reason:  "ChangeDetected",
		Message: secret.ResourceVersion,
	})

	return nil
}

// SetupWithManager setup this controller inside the controller manager
func (r *DatabaseRoleReconciler) SetupWithManager(mgr ctrl.Manager, maxConcurrentReconciles int) error {
	rolesSecretsPredicate := predicate.Funcs{
		CreateFunc: func(e event.CreateEvent) bool {
			return hasReloadLabelSet(e.Object)
		},
		DeleteFunc: func(e event.DeleteEvent) bool {
			return hasReloadLabelSet(e.Object)
		},
		GenericFunc: func(e event.GenericEvent) bool {
			return hasReloadLabelSet(e.Object)
		},
		UpdateFunc: func(e event.UpdateEvent) bool {
			return hasReloadLabelSet(e.ObjectNew)
		},
	}

	// Only consider secrets that carry both a CA certificate and a private key.
	// Bring-your-own-CA secrets (cert-only) cannot be used to sign new certs,
	// so a change to them does not need to trigger role reconciliation.
	caSecretPredicate := predicate.NewPredicateFuncs(func(obj client.Object) bool {
		secret, ok := obj.(*corev1.Secret)
		if !ok {
			return false
		}
		_, hasCACert := secret.Data[certs.CACertKey]
		_, hasCAKey := secret.Data[certs.CAPrivateKeyKey]
		return hasCACert && hasCAKey
	})

	return ctrl.NewControllerManagedBy(mgr).
		WithOptions(controller.Options{MaxConcurrentReconciles: maxConcurrentReconciles}).
		For(&apiv1.DatabaseRole{}).
		Named("database-role").
		Watches(
			&corev1.Secret{},
			handler.EnqueueRequestsFromMapFunc(r.mapSecretToRole()),
			builder.WithPredicates(rolesSecretsPredicate),
		).
		// Cert secrets owned by a DatabaseRole: re-enqueue the owner on any change
		// so that an externally deleted or modified cert is promptly regenerated.
		Owns(&corev1.Secret{}).
		// CA secrets: when the cluster's client CA rotates, re-issue certs for all
		// DatabaseRoles that reference that cluster.
		Watches(
			&corev1.Secret{},
			handler.EnqueueRequestsFromMapFunc(r.mapClientCASecretToRoles()),
			builder.WithPredicates(caSecretPredicate),
		).
		// Cluster: when a cluster appears or its spec changes, (re)evaluate the
		// roles that reference it. The generation predicate skips the frequent
		// status-only updates that would otherwise churn every referencing role.
		Watches(
			&apiv1.Cluster{},
			handler.EnqueueRequestsFromMapFunc(r.mapClusterToRoles()),
			builder.WithPredicates(predicate.GenerationChangedPredicate{}),
		).
		Complete(r)
}

// mapSecretToRole returns a function mapping secret events to the roles using them
// as password secrets.
func (r *DatabaseRoleReconciler) mapSecretToRole() handler.MapFunc {
	return func(ctx context.Context, obj client.Object) (result []reconcile.Request) {
		secret, ok := obj.(*corev1.Secret)
		if !ok {
			return nil
		}

		var roles apiv1.DatabaseRoleList
		if err := r.List(ctx, &roles, client.InNamespace(secret.Namespace)); err != nil {
			log.FromContext(ctx).Error(err, "while listing roles for secret",
				"namespace", secret.Namespace, "secret", secret.Name)
			return nil
		}

		filteredRoles := getRolesUsingSecret(roles, secret)
		result = make([]reconcile.Request, len(filteredRoles))
		for idx, value := range filteredRoles {
			result[idx] = reconcile.Request{NamespacedName: value}
		}
		return result
	}
}

// mapClientCASecretToRoles returns a function that enqueues all DatabaseRoles
// whose cluster uses the changed Secret as its client CA.
func (r *DatabaseRoleReconciler) mapClientCASecretToRoles() handler.MapFunc {
	return func(ctx context.Context, obj client.Object) []reconcile.Request {
		secret, ok := obj.(*corev1.Secret)
		if !ok {
			return nil
		}

		var clusters apiv1.ClusterList
		if err := r.List(ctx, &clusters, client.InNamespace(secret.Namespace)); err != nil {
			log.FromContext(ctx).Error(err, "while listing clusters for CA secret",
				"secret", secret.Name)
			return nil
		}

		// Collect the clusters whose client CA is the changed Secret.
		matchingClusters := make(map[string]struct{})
		for i := range clusters.Items {
			if clusters.Items[i].GetClientCASecretName() == secret.Name {
				matchingClusters[clusters.Items[i].Name] = struct{}{}
			}
		}
		if len(matchingClusters) == 0 {
			return nil
		}

		var roles apiv1.DatabaseRoleList
		if err := r.List(ctx, &roles, client.InNamespace(secret.Namespace)); err != nil {
			log.FromContext(ctx).Error(err, "while listing roles for CA secret", "secret", secret.Name)
			return nil
		}

		var result []reconcile.Request
		for i := range roles.Items {
			role := &roles.Items[i]
			if !role.IsClientCertificateEnabled() {
				continue
			}
			if _, ok := matchingClusters[role.Spec.ClusterRef.Name]; ok {
				result = append(result, reconcile.Request{
					NamespacedName: types.NamespacedName{Name: role.Name, Namespace: role.Namespace},
				})
			}
		}
		return result
	}
}

// mapClusterToRoles returns a function that enqueues all DatabaseRoles
// referencing the changed Cluster.
func (r *DatabaseRoleReconciler) mapClusterToRoles() handler.MapFunc {
	return func(ctx context.Context, obj client.Object) []reconcile.Request {
		cluster, ok := obj.(*apiv1.Cluster)
		if !ok {
			return nil
		}

		var roles apiv1.DatabaseRoleList
		if err := r.List(ctx, &roles, client.InNamespace(cluster.Namespace)); err != nil {
			log.FromContext(ctx).Error(err, "while listing roles for cluster", "cluster", cluster.Name)
			return nil
		}

		var result []reconcile.Request
		for i := range roles.Items {
			role := &roles.Items[i]
			if role.Spec.ClusterRef.Name == cluster.Name {
				result = append(result, reconcile.Request{
					NamespacedName: types.NamespacedName{Name: role.Name, Namespace: role.Namespace},
				})
			}
		}
		return result
	}
}

// getRolesUsingSecret returns the namespaced names of roles that reference the
// given secret as their password secret.
func getRolesUsingSecret(roles apiv1.DatabaseRoleList, secret *corev1.Secret) (requests []types.NamespacedName) {
	for i := range roles.Items {
		role := &roles.Items[i]
		if role.GetPasswordSecretName() == secret.Name {
			requests = append(requests,
				types.NamespacedName{
					Name:      role.Name,
					Namespace: role.Namespace,
				})
		}
	}
	return requests
}
