/*
Copyright © contributors to CloudNativePG, established as
CloudNativePG a Series of LF Projects, LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package controller

import (
	"context"
	"fmt"
	"reflect"
	"time"

	"github.com/cloudnative-pg/machinery/pkg/log"
	corev1 "k8s.io/api/core/v1"
	apierrs "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/wait"
	"k8s.io/client-go/tools/record"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/builder"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	apiv1 "github.com/cloudnative-pg/cloudnative-pg/api/v1"
	"github.com/cloudnative-pg/cloudnative-pg/pkg/certs"
)

// DatabaseRoleReconciler reconciles a DatabaseRole object
type DatabaseRoleReconciler struct {
	client.Client
	Scheme   *runtime.Scheme
	Recorder record.EventRecorder
}

// roleSecretReconcileInterval is the requeue period for roles whose client
// certificate or password is generated by the operator, ensuring both are
// renewed before expiry even in the absence of a triggering event.
const roleSecretReconcileInterval = time.Hour

// roleStatusPatchBackoff paces the retry of a role status patch: five attempts
// spaced 250ms and doubling, so at most about 4.1s of waiting once the jitter
// is counted in.
var roleStatusPatchBackoff = wait.Backoff{
	Duration: 250 * time.Millisecond,
	Factor:   2,
	Steps:    5,
	Jitter:   0.1,
}

// roleStatusPatchTimeout caps the whole retry, the waits and the round trips
// together: a reconciliation holds one of the controller's workers for as long
// as it runs, so it must not sit on the API server for longer than this.
const roleStatusPatchTimeout = 5 * time.Second

// +kubebuilder:rbac:groups=postgresql.cnpg.io,resources=databaseroles,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=postgresql.cnpg.io,resources=databaseroles/status,verbs=get;update;patch;watch
// +kubebuilder:rbac:groups=postgresql.cnpg.io,resources=databaseroles/finalizers,verbs=update
// +kubebuilder:rbac:groups=postgresql.cnpg.io,resources=clusters,verbs=get;list;watch
// +kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile implements the main reconciliation loop for Role objects
func (r *DatabaseRoleReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	contextLogger, ctx := log.SetupLogger(ctx)

	var role apiv1.DatabaseRole
	if err := r.Get(ctx, req.NamespacedName, &role); err != nil {
		if apierrs.IsNotFound(err) {
			contextLogger.Info("Resource has been deleted")
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, fmt.Errorf("cannot get the role resource: %w", err)
	}

	// A deleted role is waiting for the instance manager to resolve its
	// finalizer: generating a secret for it is pointless, and rotating the
	// password of a role that is about to be retained would leave it with a
	// credential nobody ever got to read.
	if !role.DeletionTimestamp.IsZero() {
		return ctrl.Result{}, nil
	}

	origRole := role.DeepCopy()

	// Both the password and the client certificate are generated out of the
	// cluster the role belongs to, and neither is generated while it is missing.
	cluster, err := r.getReferencedCluster(ctx, &role)
	if err != nil {
		return ctrl.Result{}, err
	}

	// The password Secret is reconciled before the condition that tracks it, so
	// that a freshly generated password is picked up by the instance manager in
	// this same loop.
	if err := r.reconcilePassword(ctx, &role, cluster); err != nil {
		return ctrl.Result{}, err
	}

	// A password the operator will not generate, or a Secret it will not touch,
	// is otherwise recorded only in a nested status field, which nothing shows
	// by default: an event puts the reason in `kubectl describe`. It is emitted
	// on a change of the explanation, not on every loop, so a condition that
	// lasts does not fill the event stream with copies of itself.
	if message := passwordMessage(&role); message != "" && message != passwordMessage(origRole) {
		r.Recorder.Event(&role, "Warning", "PasswordGenerationSkipped", message)
	}

	if err := r.reconcilePasswordCondition(ctx, &role); err != nil {
		return ctrl.Result{}, err
	}

	// A failure here must not cost us the status of the password: the
	// PasswordSecretChange condition is how the instance manager learns that a
	// password has just been rotated, and dropping it would leave the new
	// password in its Secret and never applied to PostgreSQL.
	certErr := r.reconcileClientCertificate(ctx, &role, cluster)

	// A certificate the operator will not issue is recorded the same way, and
	// for the same reason, as a password it will not generate.
	if message := certificateMessage(&role); message != "" && message != certificateMessage(origRole) {
		r.Recorder.Event(&role, "Warning", "ClientCertificateIssuanceSkipped", message)
	}

	// A manual password rotation request is consumed by removing the
	// annotation that asked for it once reconcilePassword has acted on it.
	// Patch that separately from the status, which the instance manager also
	// writes to and which this Patch (on the main resource, not the /status
	// subresource) does not touch. The patch is applied to a copy: the API
	// server answers with the stored object, whose status does not carry the
	// changes still only held in memory here, and unmarshalling that over
	// `role` would lose them before they are persisted below.
	if !reflect.DeepEqual(origRole.Annotations, role.Annotations) {
		annotated := role.DeepCopy()
		if err := r.Patch(ctx, annotated, client.MergeFrom(origRole)); err != nil {
			return ctrl.Result{}, fmt.Errorf("while patching role annotations: %w", err)
		}
	}

	if !reflect.DeepEqual(origRole.Status, role.Status) {
		if err := r.patchRoleStatus(ctx, &role); err != nil {
			return ctrl.Result{}, err
		}
	}

	if certErr != nil {
		return ctrl.Result{}, certErr
	}

	if next := nextRoleSecretReconcile(&role); next > 0 {
		return ctrl.Result{RequeueAfter: next}, nil
	}
	return ctrl.Result{}, nil
}

// patchRoleStatus persists the part of the role status this controller owns:
// the Password state, the ClientCertificate state and the PasswordSecretChange
// condition. The instance manager owns every other field, so the write is a
// merge patch.
//
// The patch is retried because losing it costs more than a delay.
// `status.password.issuedAt` is what the rotation deadline is computed from, so
// a password written to its Secret whose issue time never reaches the status is
// rotated again on the next loop; and a PasswordSecretChange condition that
// never lands leaves the new password sitting in its Secret, never applied to
// PostgreSQL.
//
// Every attempt re-reads the role and replays those fields onto it, in the
// shape of resources.RetryWithRefreshedResource, which cannot be reused here
// because its backoff is a fixed few hundred milliseconds. The condition is
// replayed one by one rather than by assigning the whole list, because
// `status.conditions` is a plain list that a merge patch replaces wholesale:
// writing our copy of it back would silently take ownership of every condition
// on the role, which is the opposite of what the two writers of this status
// agreed to do.
func (r *DatabaseRoleReconciler) patchRoleStatus(ctx context.Context, role *apiv1.DatabaseRole) error {
	ctx, cancel := context.WithTimeout(ctx, roleStatusPatchTimeout)
	defer cancel()

	key := client.ObjectKeyFromObject(role)
	password := role.Status.Password
	clientCertificate := role.Status.ClientCertificate
	condition := meta.FindStatusCondition(role.Status.Conditions, string(apiv1.ConditionPasswordSecretChange))

	// The condition function reports failure as `(false, nil)` so that the
	// backoff keeps going: returning the error would abort the loop on the
	// first attempt. The error itself is kept aside to be reported once the
	// attempts run out.
	var lastErr error
	err := wait.ExponentialBackoffWithContext(ctx, roleStatusPatchBackoff,
		func(ctx context.Context) (bool, error) {
			var latest apiv1.DatabaseRole
			if err := r.Get(ctx, key, &latest); err != nil {
				// The role was deleted while we were reconciling it: there is
				// no status left to write, and no point spending the remaining
				// attempts discovering that again.
				if apierrs.IsNotFound(err) {
					return true, nil
				}
				lastErr = err
				return false, nil
			}

			base := latest.DeepCopy()
			latest.Status.Password = password
			latest.Status.ClientCertificate = clientCertificate
			if condition != nil {
				meta.SetStatusCondition(&latest.Status.Conditions, *condition)
			} else {
				// reconcilePasswordCondition removes the condition when the
				// role has no password Secret, and that removal has to be
				// replayed too.
				meta.RemoveStatusCondition(&latest.Status.Conditions,
					string(apiv1.ConditionPasswordSecretChange))
			}

			// A previous attempt may have landed after all, or the fields may
			// already hold what we computed.
			if reflect.DeepEqual(base.Status, latest.Status) {
				return true, nil
			}

			if err := r.Status().Patch(ctx, &latest, client.MergeFrom(base)); err != nil {
				lastErr = err
				return false, nil
			}
			return true, nil
		})
	if err == nil {
		return nil
	}
	if lastErr != nil {
		return fmt.Errorf("while patching role status: %w", lastErr)
	}
	return fmt.Errorf("while patching role status: %w", err)
}

// nextRoleSecretReconcile returns how long from now the role's client
// certificate or password should next be checked for renewal, or zero when
// neither is enabled. The certificate falls back to the fixed
// roleSecretReconcileInterval; the password instead requeues right at its
// renewal deadline, since duration/renewBefore can be far shorter than that
// interval, and a flat hourly check would leave a short-lived password
// overdue for most of its remaining life.
func nextRoleSecretReconcile(role *apiv1.DatabaseRole) time.Duration {
	var next time.Duration
	certEnabled := role.IsClientCertificateEnabled()
	if certEnabled {
		next = roleSecretReconcileInterval
	}

	if role.IsPasswordRotationEnabled() {
		untilRenewal := untilPasswordRenewal(role)
		if !certEnabled || untilRenewal < next {
			next = untilRenewal
		}
	}

	return next
}

// untilPasswordRenewal returns how long from now the password of the role is
// due for renewal, falling back to the fixed roleSecretReconcileInterval when
// its recorded expiration cannot be read, and flooring at one second when the
// deadline has already passed, since a zero or negative RequeueAfter would
// mean no further requeue at all rather than a prompt retry.
func untilPasswordRenewal(role *apiv1.DatabaseRole) time.Duration {
	if role.Status.Password == nil || role.Status.Password.Expiration == "" {
		return roleSecretReconcileInterval
	}

	expiration, err := time.Parse(time.RFC3339, role.Status.Password.Expiration)
	if err != nil {
		return roleSecretReconcileInterval
	}

	renewalDue := expiration.Add(-passwordRenewBefore(role))
	if untilRenewal := time.Until(renewalDue); untilRenewal > 0 {
		return untilRenewal
	}

	// The deadline is in the past and the status says why the operator cannot
	// act on it: a Secret it does not own, an unsatisfiable criteria, a replica
	// cluster. None of those clears on its own, so retrying every second would
	// spin for as long as the condition lasts, while resolving it changes the
	// role or its Secret and reconciles it at once anyway.
	if role.Status.Password.Message != "" {
		return roleSecretReconcileInterval
	}

	return time.Second
}

// reconcilePasswordCondition manages the ConditionPasswordSecretChange status condition.
// If the role has no password secret, the condition is removed. If the secret is found,
// the condition is set with the secret's ResourceVersion so the instance manager can
// detect when the password changed. The condition is only updated in memory: the caller
// persists it together with the rest of the status the operator owns.
func (r *DatabaseRoleReconciler) reconcilePasswordCondition(
	ctx context.Context,
	role *apiv1.DatabaseRole,
) error {
	secretName := role.GetPasswordSecretName()
	if secretName == "" {
		// If the password secret was removed, clear any stale PasswordSecretChange
		// condition left over from a previously configured secret.
		meta.RemoveStatusCondition(&role.Status.Conditions, string(apiv1.ConditionPasswordSecretChange))
		return nil
	}

	var secret corev1.Secret
	if err := r.Get(ctx, types.NamespacedName{
		Namespace: role.Namespace,
		Name:      secretName,
	}, &secret); err != nil {
		// There's no need to fill the operator log with errors
		// if the secret still doesn't exist.
		if apierrs.IsNotFound(err) {
			return nil
		}

		return fmt.Errorf(
			"while getting secret %q referred by role %q: %w",
			secretName,
			role.Name,
			err,
		)
	}

	// The instance manager, which runs the controller that applies the Role spec
	// to the PostgreSQL database, cannot watch Secrets directly. Granting that
	// permission would allow it to watch all Secrets in the namespace, which is
	// undesirable from a security standpoint. Unfortunately, the Kubernetes API
	// does not support watching a specific subset of Secrets.
	//
	// To work around this, the operator (which has the necessary permissions)
	// watches Secrets and detects changes to those referenced by Role objects.
	// When a change is detected, the operator updates a condition on the Role,
	// storing the Secret's ResourceVersion. This status update triggers a
	// reconciliation cycle in the instance manager, which then reads the updated
	// password and applies it to PostgreSQL.
	meta.SetStatusCondition(&role.Status.Conditions, metav1.Condition{
		Type:    string(apiv1.ConditionPasswordSecretChange),
		Status:  metav1.ConditionTrue,
		Reason:  "ChangeDetected",
		Message: secret.ResourceVersion,
	})

	return nil
}

// SetupWithManager setup this controller inside the controller manager
func (r *DatabaseRoleReconciler) SetupWithManager(mgr ctrl.Manager, maxConcurrentReconciles int) error {
	rolesSecretsPredicate := predicate.Funcs{
		CreateFunc: func(e event.CreateEvent) bool {
			return hasReloadLabelSet(e.Object)
		},
		DeleteFunc: func(e event.DeleteEvent) bool {
			return hasReloadLabelSet(e.Object)
		},
		GenericFunc: func(e event.GenericEvent) bool {
			return hasReloadLabelSet(e.Object)
		},
		UpdateFunc: func(e event.UpdateEvent) bool {
			return hasReloadLabelSet(e.ObjectNew)
		},
	}

	// Only consider secrets that carry both a CA certificate and a private key.
	// Bring-your-own-CA secrets (cert-only) cannot be used to sign new certs,
	// so a change to them does not need to trigger role reconciliation.
	caSecretPredicate := predicate.NewPredicateFuncs(func(obj client.Object) bool {
		secret, ok := obj.(*corev1.Secret)
		if !ok {
			return false
		}
		_, hasCACert := secret.Data[certs.CACertKey]
		_, hasCAKey := secret.Data[certs.CAPrivateKeyKey]
		return hasCACert && hasCAKey
	})

	return ctrl.NewControllerManagedBy(mgr).
		WithOptions(controller.Options{MaxConcurrentReconciles: maxConcurrentReconciles}).
		For(&apiv1.DatabaseRole{}).
		Named("database-role").
		Watches(
			&corev1.Secret{},
			handler.EnqueueRequestsFromMapFunc(r.mapSecretToRole()),
			builder.WithPredicates(rolesSecretsPredicate),
		).
		// Cert secrets owned by a DatabaseRole: re-enqueue the owner on any change
		// so that an externally deleted or modified cert is promptly regenerated.
		Owns(&corev1.Secret{}).
		// CA secrets: when the cluster's client CA rotates, re-issue certs for all
		// DatabaseRoles that reference that cluster.
		Watches(
			&corev1.Secret{},
			handler.EnqueueRequestsFromMapFunc(r.mapClientCASecretToRoles()),
			builder.WithPredicates(caSecretPredicate),
		).
		// Cluster: when a cluster appears or its spec changes, (re)evaluate the
		// roles that reference it. The generation predicate skips the frequent
		// status-only updates that would otherwise churn every referencing role.
		Watches(
			&apiv1.Cluster{},
			handler.EnqueueRequestsFromMapFunc(r.mapClusterToRoles()),
			builder.WithPredicates(predicate.GenerationChangedPredicate{}),
		).
		Complete(r)
}

// mapSecretToRole returns a function mapping secret events to the roles using them
// as password secrets.
func (r *DatabaseRoleReconciler) mapSecretToRole() handler.MapFunc {
	return func(ctx context.Context, obj client.Object) (result []reconcile.Request) {
		secret, ok := obj.(*corev1.Secret)
		if !ok {
			return nil
		}

		var roles apiv1.DatabaseRoleList
		if err := r.List(ctx, &roles, client.InNamespace(secret.Namespace)); err != nil {
			log.FromContext(ctx).Error(err, "while listing roles for secret",
				"namespace", secret.Namespace, "secret", secret.Name)
			return nil
		}

		filteredRoles := getRolesUsingSecret(roles, secret)
		result = make([]reconcile.Request, len(filteredRoles))
		for idx, value := range filteredRoles {
			result[idx] = reconcile.Request{NamespacedName: value}
		}
		return result
	}
}

// mapClientCASecretToRoles returns a function that enqueues all DatabaseRoles
// whose cluster uses the changed Secret as its client CA.
func (r *DatabaseRoleReconciler) mapClientCASecretToRoles() handler.MapFunc {
	return func(ctx context.Context, obj client.Object) []reconcile.Request {
		secret, ok := obj.(*corev1.Secret)
		if !ok {
			return nil
		}

		var clusters apiv1.ClusterList
		if err := r.List(ctx, &clusters, client.InNamespace(secret.Namespace)); err != nil {
			log.FromContext(ctx).Error(err, "while listing clusters for CA secret",
				"secret", secret.Name)
			return nil
		}

		// Collect the clusters whose client CA is the changed Secret.
		matchingClusters := make(map[string]struct{})
		for i := range clusters.Items {
			if clusters.Items[i].GetClientCASecretName() == secret.Name {
				matchingClusters[clusters.Items[i].Name] = struct{}{}
			}
		}
		if len(matchingClusters) == 0 {
			return nil
		}

		var roles apiv1.DatabaseRoleList
		if err := r.List(ctx, &roles, client.InNamespace(secret.Namespace)); err != nil {
			log.FromContext(ctx).Error(err, "while listing roles for CA secret", "secret", secret.Name)
			return nil
		}

		var result []reconcile.Request
		for i := range roles.Items {
			role := &roles.Items[i]
			if !role.IsClientCertificateEnabled() {
				continue
			}
			if _, ok := matchingClusters[role.Spec.ClusterRef.Name]; ok {
				result = append(result, reconcile.Request{
					NamespacedName: types.NamespacedName{Name: role.Name, Namespace: role.Namespace},
				})
			}
		}
		return result
	}
}

// mapClusterToRoles returns a function that enqueues all DatabaseRoles
// referencing the changed Cluster.
func (r *DatabaseRoleReconciler) mapClusterToRoles() handler.MapFunc {
	return func(ctx context.Context, obj client.Object) []reconcile.Request {
		cluster, ok := obj.(*apiv1.Cluster)
		if !ok {
			return nil
		}

		var roles apiv1.DatabaseRoleList
		if err := r.List(ctx, &roles, client.InNamespace(cluster.Namespace)); err != nil {
			log.FromContext(ctx).Error(err, "while listing roles for cluster", "cluster", cluster.Name)
			return nil
		}

		var result []reconcile.Request
		for i := range roles.Items {
			role := &roles.Items[i]
			if role.Spec.ClusterRef.Name == cluster.Name {
				result = append(result, reconcile.Request{
					NamespacedName: types.NamespacedName{Name: role.Name, Namespace: role.Namespace},
				})
			}
		}
		return result
	}
}

// getRolesUsingSecret returns the namespaced names of roles that reference the
// given secret as their password secret.
func getRolesUsingSecret(roles apiv1.DatabaseRoleList, secret *corev1.Secret) (requests []types.NamespacedName) {
	for i := range roles.Items {
		role := &roles.Items[i]
		if role.GetPasswordSecretName() == secret.Name {
			requests = append(requests,
				types.NamespacedName{
					Name:      role.Name,
					Namespace: role.Namespace,
				})
		}
	}
	return requests
}
