apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:13.14

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      postInitApplicationSQL:
        - create table numbers (i serial primary key, m integer)
        - insert into numbers (m) (select generate_series(1,10000))
        - alter table numbers owner to app;
        - create table numbers_two (i serial primary key, m integer)
        - insert into numbers_two (m) (select generate_series(1,10000))
        - alter table numbers_two owner to app;
        - create table numbers_three (i serial primary key, m integer)
        - insert into numbers_three (m) (select generate_series(1,10000))
        - alter table numbers_three owner to app;

  # This is needed to enable users to create the publication while
  # they are connected from the destination. Like in:
  #
  #     ./bin/kubectl-cnpg publication create cluster-example-dest --external-cluster=cluster-example \
  #        --dbname=app \
  #        --publication=app \ 
  #        --all-tables
  #
  # Without superuser access, this would fail with:
  #
  #     Executing: CREATE PUBLICATION "app" FOR ALL TABLES
  #     ERROR:  must be superuser to create FOR ALL TABLES publication
  #    command terminated with exit code 1
  enableSuperuserAccess: true

  managed:
    roles:
      - name: app
        login: true
        replication: true

# To create the publication while connected to the source side, use:
#
#     ./bin/kubectl-cnpg publication create cluster-example --publication=app --all-tables
#
#     Executing: CREATE PUBLICATION "app" FOR ALL TABLES
#     CREATE PUBLICATION