apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-dest
spec:
  instances: 1

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      import:
        type: microservice
        schemaOnly: true
        databases:
          - app
        source:
          externalCluster: cluster-example

  externalClusters:
  - name: cluster-example
    connectionParameters:
      host: cluster-example-rw.default.svc
      # We're using the superuser to allow the publication to be
      # created directly when connected to the target server.
      # See cluster-example-logical-source.yaml for more information
      # about this.
      user: postgres
      dbname: app
    password:
      name: cluster-example-superuser
      key: password
