apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  postgresql:
    pg_hba:
      - hostssl app all all cert

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 1Gi
