apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3

  postgresql:
    synchronous:
      method: any
      number: 1
    pg_hba:
      - hostssl app all all cert

  storage:
    size: 1Gi
