apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-syncreplicas
spec:
  instances: 5

  minSyncReplicas: 3
  maxSyncReplicas: 4

  postgresql:
    minSyncReplicasEnforcement: required

  storage:
    size: 1G
