apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore
spec:
  instances: 3

  storage:
    size: 1Gi
    storageClass: csi-hostpath-sc

  bootstrap:
    recovery:
      volumeSnapshots:
        storage:
          name: cluster-example-with-backup-3-1692618163
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io

