apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore-pitr
spec:
  instances: 3

  storage:
    size: 1Gi
    storageClass: csi-hostpath-sc

  externalClusters:
    - name: origin

      barmanObjectStore:
        serverName: cluster-example-with-backup
        destinationPath: s3://backups/
        endpointURL: http://minio:9000
        s3Credentials:
          accessKeyId:
            name: minio
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: minio
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8

  bootstrap:
    recovery:
      source: origin

      recoveryTarget:
        targetTime: "2023-08-21 12:00:00.00000+00"

      volumeSnapshots:
        storage:
          name: cluster-example-with-backup-3-1692618163
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
