apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore-full
spec:
  instances: 3

  storage:
    size: 1Gi
    storageClass: csi-hostpath-sc

  bootstrap:
    recovery:
      volumeSnapshots:
        storage:
          name: cluster-example-2-1695821489
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
