apiVersion: postgresql.k8s.2ndq.io/v1alpha1
kind: Cluster
metadata:
  name: cluster-example-secret
spec:
  instances: 3

  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: cluster-example-app-user

  superuserSecret:
    name: cluster-example-superuser

  storage:
    size: 1Gi
---
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  username: YXBwdXNlcg==
kind: Secret
metadata:
  name: cluster-example-app-user
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: cluster-example-superuser
type: kubernetes.io/basic-auth
