apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: image-catalog-example
spec:
  images:
    - image: ghcr.io/cloudnative-pg/postgresql:17
      major: 17
  extraImages:
    - key: pgbouncer
      image: ghcr.io/cloudnative-pg/pgbouncer:1.24.0
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: image-catalog-example
    major: 17
  storage:
    size: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-example-rw
spec:
  cluster:
    name: cluster-example
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    imageCatalogRef:
      apiGroup: postgresql.cnpg.io
      kind: ImageCatalog
      name: image-catalog-example
      key: pgbouncer
