apiVersion: operators.coreos.com/v1
kind: Subscription
metadata:
  name: cloud-native-postgresql
  namespace: openshift-operators
spec:
  channel: beta
  name: cloud-native-postgresql
  source: certified-operators
  sourceNamespace: openshift-marketplace
