apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cloudnative-pg
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/name: cloudnative-pg
