# permissions for end users to view backups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-viewer-role
rules:
- apiGroups:
  - postgresqlx.cnpg.io
  resources:
  - backups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresqlx.cnpg.io
  resources:
  - backups/status
  verbs:
  - get
