# permissions for end users to view databases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudnative-pg-kubebuilderv4
    app.kubernetes.io/managed-by: kustomize
  name: database-viewer-role
rules:
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - databases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - databases/status
  verbs:
  - get
