# permissions for end users to view poolers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pooler-viewer-role
rules:
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - poolers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - poolers/status
  verbs:
  - get
