name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["cloudnative-pg/cloudnative-pg"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for CloudNativePg!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What is the exact version of CloudNativePG you are running?
      placeholder: Tell us the version of the operator
      value: "1.XX.Y"
    validations:
      required: true
  - type: dropdown
    id: k8s_version
    attributes:
      label: What version of Kubernetes are you using?
      options:
        - 1.28
        - 1.27
        - 1.26
        - 1.25
        - 1.24 (unsupported)
        - 1.23 (unsupported)
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

