name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["cloudnative-pg/cloudnative-pg"]
assignees: ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for CloudNativePg!
  - type: checkboxes
    id: terms
    attributes:
      label: Is there an existing issue already for this bug?
      description: Before you submit a bug, make sure you have searched if a similar one already exists
      options:
        - label: I have searched for an existing issue, and could not find anything. I believe this is a new bug.
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: I have read the troubleshooting guide
      description: Before you submit a bug, make sure you have read the ["Common issues" section in the Troubleshooting guide](https://cloudnative-pg.io/documentation/current/troubleshooting/#some-common-issues).
      options:
        - label: I have read the troubleshooting guide and I think this is a new bug.
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: I am running a supported version of CloudNativePG
      description: Before you submit a bug, make sure you have read ["Supported releases"](https://cloudnative-pg.io/documentation/current/supported_releases/) and that you are running a supported version of CloudNativePG with the latest patch/security fixes, or you are working on the current trunk (`main` branch)
      options:
        - label: I have read the troubleshooting guide and I think this is a new bug.
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What is the version of CloudNativePG you are running?
    validations:
      options:
        - 1.21.0 
        - 1.20.3
        - 1.19.5
        - trunk (main)
        - older in 1.20.x
        - older in 1.19.x
        - older minor (unsupported)
    validations:
      required: false
  - type: dropdown
    id: k8s_version
    attributes:
      label: What version of Kubernetes are you using?
      options:
        - 1.28
        - 1.27
        - 1.26
        - 1.25
        - 1.24 (unsupported)
        - 1.23 (unsupported)
        - other (unsupported)
    validations:
      required: false
  - type: dropdown
    id: k8s_environment
    attributes:
      label: What is your Kubernetes environment?
      options:
        - Self-managed
        - Cloud: Amazon EKS
        - Cloud: Google GKE
        - Cloud: Azure AKS
        - Cloud: Other
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: spec
    attributes:
      label: Cluster definition
      description: Please copy and paste the CRD of the cluster
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

