{
 "title": "CloudNativePG",
 "tags": [ "cloudnativepg" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "cnpg_collector_up" } },
   {
    "name": "cluster",
    "query": {
     "query": "cnpg_collector_up{namespace=~\"$namespace\"}"
    }
   },
   {
    "name": "instances",
    "query": {
     "query": "cnpg_collector_up{namespace=~\"$namespace\",pod=~\"$cluster-[0-9]+$\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 } },
  { "title": "Overview", "type": "text", "gridPos": { "h": 1, "w": 15, "x": 3, "y": 0 } },
  { "title": "Storage", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 18, "y": 0 } },
  { "title": "Backups", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 21, "y": 0 } },
  {
   "title": "Last failover",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_postmaster_start_time{namespace=~\"$namespace\",pod=~\"$instances\"})*1000"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{namespace=~\"$namespace\",pod=~\"$instances\"}[$__interval])) + sum(rate(cnpg_pg_stat_database_xact_rollback{namespace=~\"$namespace\",pod=~\"$instances\"}[$__interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "description": "CPU Utilisation from Requests",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",  namespace=\"$namespace\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "gauge",
   "description": "Memory Utilisation from Requests",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) / sum(max by(pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}))"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_replication_lag{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_stat_replication_write_lag_seconds{namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"}))",
     "legendFormat": "DATA"
    },
    {
     "expr": "max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"}))",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "title": "Last Base Backup",
   "type": "stat",
   "description": "Elapsed time since the last successful base backup.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-(time() - max(cnpg_collector_last_available_backup_timestamp{namespace=\"$namespace\",pod=~\"$instances\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last archived WAL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\",pod=~\"$instances\"} + cnpg_pg_replication_is_wal_receiver_up{namespace=~\"$namespace\",pod=~\"$instances\"}) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\",pod=~\"$instances\"}) -\ncnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\",pod=~\"$instances\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_collector_postgres_version{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flush Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_stat_replication_flush_lag_seconds{namespace=~\"$namespace\",pod=~\"$cluster-[0-9]+$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replay Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_stat_replication_replay_lag_seconds{namespace=~\"$namespace\",pod=~\"$cluster-[0-9]+$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Excluding cache",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$instances\", namespace=\"$namespace\", container!=\"\", image!=\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_database_size_bytes{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "First Recoverability Point",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_collector_first_recoverability_point{namespace=~\"$namespace\",pod=~\"$instances\"})*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Server Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Clustering / replicas",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Zone",
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Wraparound",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Started",
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 20, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 22, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "repeat": "instances",
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$instances</p>\n  </td>\n</table>"
   },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 9 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 9 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\",pod=~\"$instances\"} + cnpg_pg_replication_is_wal_receiver_up{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 7, "y": 9 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_replication_streaming_replicas{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This metric depends on exporting the: `topology.kubernetes.io/zone` label through kube-state-metrics (not enabled by default). Can be added by changing its configuration with:\n\n```yaml\nmetricLabelsAllowlist:\n  - nodes=[topology.kubernetes.io/zone]\n```",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\",pod=~\"$instances\"} * on(node,instance) group_left(label_topology_kubernetes_io_zone) kube_node_labels",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 9 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (cnpg_backends_total{namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "-"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 9 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum by (pod) (cnpg_backends_total{namespace=~\"$namespace\",pod=~\"$instances\"}) / sum by (pod) (cnpg_pg_settings_setting{name=\"max_connections\",namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 9 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (cnpg_pg_database_xid_age{namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_postmaster_start_time{namespace=~\"$namespace\",pod=~\"$instances\"}*1000"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_collector_postgres_version{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 3, "y": 19 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Effective Cache Size",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 9, "y": 19 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 15, "y": 19 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sequential Page Cost",
   "type": "text",
   "gridPos": { "h": 1, "w": 3, "x": 21, "y": 19 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "repeat": "instances",
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$instances</p>\n  </td>\n</table>"
   },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{name=\"max_connections\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (cnpg_pg_settings_setting{name=\"shared_buffers\",namespace=~\"$namespace\",pod=~\"$instances\"}) * max by (pod) (cnpg_pg_settings_setting{name=\"block_size\",namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 20 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (cnpg_pg_settings_setting{name=\"effective_cache_size\",namespace=~\"$namespace\",pod=~\"$instances\"}) * max by (pod) (cnpg_pg_settings_setting{name=\"block_size\",namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 20 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{name=\"work_mem\",namespace=~\"$namespace\",pod=~\"$instances\"} * 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 20 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{name=\"maintenance_work_mem\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 20 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{name=\"random_page_cost\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 20 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{name=\"seq_page_cost\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Configurations",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Operational Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$instances\", namespace=~\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$instances\", namespace=~\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"$instances\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"$instances\", namespace=\"$namespace\", container!=\"\", image!=\"\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Session States",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(cnpg_backends_total{namespace=~\"$namespace\",pod=~\"$instances\"}) by (pod)",
       "legendFormat": "total ({{pod}})"
      },
      {
       "expr": "sum(cnpg_backends_total{namespace=~\"$namespace\",pod=~\"$instances\"}) by (state, pod)",
       "legendFormat": "{{state}} ({{pod}})"
      }
     ]
    },
    {
     "title": "Transactions [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])) by (pod)",
       "legendFormat": "committed ({{pod}})"
      },
      {
       "expr": "sum(rate(cnpg_pg_stat_database_xact_rollback{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])) by (pod)",
       "legendFormat": "rolled back ({{pod}})"
      }
     ]
    },
    {
     "title": "Longest Transaction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod) (cnpg_backends_max_tx_duration_seconds{namespace=~\"$namespace\",pod=~\"$instances\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Deadlocks [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "rate(cnpg_pg_stat_database_deadlocks{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
       "legendFormat": "count ({{pod}})"
      }
     ]
    },
    {
     "title": "Blocked Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "targets": [
      {
       "expr": "cnpg_backends_waiting_total{namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage & I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Volume Space Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Volume Inode Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"} / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Tuple I/O [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sum(rate(cnpg_pg_stat_database_tup_deleted{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
       "legendFormat": "deleted"
      },
      {
       "expr": "sum(rate(cnpg_pg_stat_database_tup_inserted{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
       "legendFormat": "inserted"
      },
      {
       "expr": "sum(rate(cnpg_pg_stat_database_tup_fetched{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
       "legendFormat": "fetched"
      },
      {
       "expr": "sum(rate(cnpg_pg_stat_database_tup_returned{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
       "legendFormat": "returned"
      },
      {
       "expr": "sum(rate(cnpg_pg_stat_database_tup_updated{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
       "legendFormat": "updated"
      }
     ]
    },
    {
     "title": "Block I/O [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "rate(cnpg_pg_stat_database_blks_hit{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
       "legendFormat": "hit ({{pod}})"
      },
      {
       "expr": "rate(cnpg_pg_stat_database_blks_read{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
       "legendFormat": "read ({{pod}})"
      }
     ]
    },
    {
     "title": "Database Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max by (datname) (cnpg_pg_database_size_bytes{datname!~\"template.*\",datname!=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"})",
       "legendFormat": " {{pod}}: {{datname}}"
      }
     ]
    },
    {
     "title": "Temp Bytes [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(cnpg_pg_stat_database_temp_bytes{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Ahead Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WAL Segment Archive Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "cnpg_collector_pg_wal_archive_status{value=\"ready\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "ready ({{pod}})"
      },
      {
       "expr": "cnpg_collector_pg_wal_archive_status{value=\"done\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "done ({{pod}})"
      }
     ]
    },
    {
     "title": "Archiver Status [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "targets": [
      {
       "expr": "rate(cnpg_pg_stat_archiver_archived_count{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
       "legendFormat": "archived ({{pod}})"
      },
      {
       "expr": "rate(cnpg_pg_stat_archiver_failed_count{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
       "legendFormat": "failed ({{pod}})"
      }
     ]
    },
    {
     "title": "Last Archive Age",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "age ({{pod}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Replication Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_replication_lag{namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Write Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_replication_write_lag_seconds{namespace=~\"$namespace\",pod=~\"$cluster-[0-9]+$\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    },
    {
     "title": "Flush Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_replication_flush_lag_seconds{namespace=~\"$namespace\",pod=~\"$cluster-[0-9]+$\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    },
    {
     "title": "Replay Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_replication_replay_lag_seconds{namespace=~\"$namespace\",pod=~\"$cluster-[0-9]+$\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Collector Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collection Duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "cnpg_collector_collection_duration_seconds{namespace=~\"$namespace\",pod=~\"$instances\"}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "cnpg_collector_last_collection_error{namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "First Recoverability Point",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "cnpg_collector_first_recoverability_point{namespace=~\"$namespace\",pod=~\"$instances\"}*1000 > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requested/Timed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_bgwriter_checkpoints_req{namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "req/{{pod}}"
      },
      {
       "expr": "cnpg_pg_stat_bgwriter_checkpoints_timed{namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "timed/{{pod}}"
      }
     ]
    },
    {
     "title": "Write/Sync time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "cnpg_pg_stat_bgwriter_checkpoint_write_time{namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "write/{{pod}}"
      },
      {
       "expr": "cnpg_pg_stat_bgwriter_checkpoint_sync_time{namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "sync/{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}