/*
This file is part of Cloud Native PostgreSQL.

Copyright (C) 2019-2020 2ndQuadrant Italia SRL. Exclusively licensed to 2ndQuadrant Limited.
*/

package postgres

import (
	"fmt"
	"path"

	"gitlab.2ndquadrant.com/k8s/cloud-native-postgresql/internal/management/utils"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/dynamic"

	"gitlab.2ndquadrant.com/k8s/cloud-native-postgresql/pkg/fileutils"
	"gitlab.2ndquadrant.com/k8s/cloud-native-postgresql/pkg/management/log"
)

// InstallCustomConfigurationFile install in the PgData the file with
// the PostgreSQL settings which have been generated by the operator
func InstallCustomConfigurationFile(pgdata, filename string) error {
	if filename == "" || pgdata == "" {
		return nil
	}

	contents, err := fileutils.ReadFile(filename)
	if err != nil {
		return fmt.Errorf("while reading custom configuration file: %w", err)
	}

	return InstallPgDataFileContent(pgdata, contents, PostgresqlCustomConfigurationFile)
}

// InstallPgHBAFile install in the PgData the file containing
// the host-based access rules which is being managed by the operator
func InstallPgHBAFile(pgdata, filename string) error {
	if filename == "" || pgdata == "" {
		return nil
	}

	contents, err := fileutils.ReadFile(filename)
	if err != nil {
		return fmt.Errorf("while reading hba file: %w", err)
	}

	return InstallPgDataFileContent(
		pgdata,
		contents,
		PostgresqlHBARulesFile)
}

// InstallPgDataFileContent install a file in PgData
func InstallPgDataFileContent(pgdata, contents, destinationFile string) error {
	log.Log.Info(
		"Installing configuration file",
		"pgdata", pgdata,
		"filename", destinationFile)

	targetFile := path.Join(pgdata, destinationFile)
	return fileutils.WriteStringToFile(targetFile, contents)
}

// RefreshConfigurationFilesFromObject receive an unstructured object representing
// a configmap and rewrite the file in the PGDATA.
// Important: this won't send a SIGHUP to the server
func (instance *Instance) RefreshConfigurationFilesFromObject(object *unstructured.Unstructured) error {
	postgresConfiguration, err := utils.GetPostgreSQLConfiguration(object)
	if err != nil {
		return err
	}

	postgresHBA, err := utils.GetPostgreSQLHBA(object)
	if err != nil {
		return err
	}

	err = InstallPgDataFileContent(
		instance.PgData,
		postgresConfiguration,
		PostgresqlCustomConfigurationFile)
	if err != nil {
		return fmt.Errorf(
			"installing postgresql configuration: %w",
			err)
	}

	err = InstallPgDataFileContent(
		instance.PgData,
		postgresHBA,
		PostgresqlHBARulesFile)
	if err != nil {
		return fmt.Errorf(
			"installing postgresql HBA rules: %w",
			err)
	}

	return nil
}

// RefreshConfigurationFiles get the latest version of the ConfigMap from the API
// server and then write the configuration in PGDATA
func (instance *Instance) RefreshConfigurationFiles(client dynamic.Interface) error {
	unstructuredObject, err := client.Resource(schema.GroupVersionResource{
		Group:    "",
		Version:  "v1",
		Resource: "configmaps",
	}).
		Namespace(instance.Namespace).
		Get(instance.ClusterName, metav1.GetOptions{})
	if err != nil {
		return err
	}

	return instance.RefreshConfigurationFilesFromObject(unstructuredObject)
}
