/*
This file is part of Cloud Native PostgreSQL.

Copyright (C) 2019-2020 2ndQuadrant Italia SRL. Exclusively licensed to 2ndQuadrant Limited.
*/

package postgres

import (
	"os"
	"path"

	"gitlab.2ndquadrant.com/k8s/cloud-native-postgresql/pkg/fileutils"
)

// InstallPgPass install a given pgpass file in the user home directory
func InstallPgPass(pgpass string) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	targetPgPass := path.Join(homeDir, ".pgpass")
	if err = fileutils.CopyFile(pgpass, targetPgPass); err != nil {
		return err
	}

	return os.Chmod(targetPgPass, 0600)
}

// InstallCustomConfigurationFile install in the PgData the file with
// the PostgreSQL settings which have been generated by the operator
func InstallCustomConfigurationFile(pgdata, filename string) error {
	return installPgDataFile(pgdata, filename, PostgresqlCustomConfigurationFile)
}

// InstallPgHBAFile install in the PgData the file containing
// the host-based access rules which is being managed by the operator
func InstallPgHBAFile(pgdata, filename string) error {
	return installPgDataFile(pgdata, filename, "pg_hba.conf")
}

// installPgDataFile install a file in PgData
func installPgDataFile(pgdata, source, destination string) error {
	targetFile := path.Join(pgdata, destination)
	return fileutils.CopyFile(source, targetFile)
}
