---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      imagePullSecrets:
      - name: cnpg-pull-secret
      securityContext:
        runAsNonRoot: true
        seccompProfile:
        runAsUser:
        runAsGroup:
      serviceAccountName: cnpg-manager
      containers:
      - name: manager
        resources:
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['olm.targetNamespaces']
          - name: WEBHOOK_CERT_DIR
            value: /apiserver.local.config/certificates
          - name: RELATED_IMAGE_CNPG
            value: $(OPERATOR_IMAGE_NAME)
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser:
          runAsGroup:
