# This patch is needed to instruct OLM to add containerPort to webhooks definition
# otherwise it will use a default that could be `0` or `443` that are both wrong
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - clientConfig:
      service:
        containerPort: 9443
    name: mcluster.cnpg.io
  - clientConfig:
      service:
        containerPort: 9443
    name: mbackup.cnpg.io
  - clientConfig:
      service:
        containerPort: 9443
    name: mscheduledbackup.cnpg.io
