/*
Copyright © contributors to CloudNativePG, established as
CloudNativePG a Series of LF Projects, LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

// Package config loads the configuration file that drives an e2e run.
// The file is the only source of run configuration: the suite reads no
// environment variables.
package config

import (
	"fmt"
	"os"
	"sync"

	"sigs.k8s.io/yaml"

	"github.com/cloudnative-pg/cloudnative-pg/pkg/versions"
)

// DefaultPath is where the suite looks for the configuration file when no
// explicit `--e2e-config` flag is passed. It is relative to the working
// directory of the test binary, i.e. tests/e2e.
const DefaultPath = "config.yaml"

// VendorKind is the cloud vendor used when the configuration does not
// specify one.
const VendorKind = "kind"

// Config drives an e2e suite run. It is loaded from a YAML file, usually
// generated by the hack/e2e scripts, and can also be hand-written to run
// the suite directly through ginkgo or an IDE.
type Config struct {
	// Postgres selects the PostgreSQL images under test
	Postgres PostgresConfiguration `json:"postgres"`

	// Storage selects the storage and volume snapshot classes used by the
	// tests. Empty fields are autodetected from the cluster before the
	// suite starts.
	Storage StorageConfiguration `json:"storage"`

	// CloudVendor is the kind of cluster the suite runs against
	// (kind, k3d, aks, eks, gke, ocp). Defaults to kind.
	CloudVendor string `json:"cloudVendor,omitempty"`

	// Depth is the test-importance threshold: specs declaring an importance
	// level deeper than this value are skipped. When absent, the suite
	// default (medium) applies.
	Depth *int `json:"depth,omitempty"`

	// LabelFilter is a ginkgo label-filter expression applied to the run.
	// When set, it overrides any --label-filter passed on the ginkgo
	// command line.
	LabelFilter string `json:"labelFilter,omitempty"`

	// SkipUpgradeSuite skips the operator upgrade specs
	SkipUpgradeSuite bool `json:"skipUpgradeSuite,omitempty"`

	// Timeouts overrides the default timeout (in seconds) of the named
	// suite events. Unknown event names are rejected at suite start.
	Timeouts map[string]int `json:"timeouts,omitempty"`

	// Deployment describes how the operator under test has been deployed
	Deployment DeploymentConfiguration `json:"deployment"`

	// RegistryPullSecret holds the credentials of a private registry the
	// upgrade tests need to pull from
	RegistryPullSecret RegistryPullSecretConfiguration `json:"registryPullSecret"`

	// Azure configures the Azure Blob Storage backend used by the
	// azure-blob backup tests
	Azure AzureConfiguration `json:"azure"`

	// PreserveNamespaces lists namespace prefixes that must not be deleted
	// at the end of a run, to ease debugging
	PreserveNamespaces []string `json:"preserveNamespaces,omitempty"`

	// BranchName is the git branch the suite is running from, used to
	// detect release branches. When empty, it is detected via git.
	BranchName string `json:"branchName,omitempty"`

	// MajorUpgrade overrides the images used by the major upgrade tests
	MajorUpgrade MajorUpgradeConfiguration `json:"majorUpgrade"`
}

// PostgresConfiguration selects the PostgreSQL images under test
type PostgresConfiguration struct {
	// Image is the PostgreSQL image the clusters are created with.
	// Defaults to the operator default image.
	Image string `json:"image,omitempty"`

	// PreRollingUpdateImage is the image the rolling update tests start
	// from before updating to Image. When empty, tests exercising a
	// rolling update fall back to Image.
	PreRollingUpdateImage string `json:"preRollingUpdateImage,omitempty"`

	// ImageRepository is the repository the official PostgreSQL images are
	// pulled from, used by tests that need images not under test (e.g.
	// major upgrade sources)
	ImageRepository string `json:"imageRepository,omitempty"`

	// PostGISImageRepository is the repository the PostGIS images are
	// pulled from
	PostGISImageRepository string `json:"postgisImageRepository,omitempty"`
}

// StorageConfiguration selects the storage and volume snapshot classes
// used by the tests
type StorageConfiguration struct {
	// StorageClass used for the PVCs created by the tests
	StorageClass string `json:"storageClass,omitempty"`

	// CSIStorageClass is a CSI-capable storage class, required by the
	// volume snapshot tests
	CSIStorageClass string `json:"csiStorageClass,omitempty"`

	// VolumeSnapshotClass used by the volume snapshot tests
	VolumeSnapshotClass string `json:"volumeSnapshotClass,omitempty"`
}

// DeploymentConfiguration describes how the operator under test has been
// deployed
type DeploymentConfiguration struct {
	// Method is the mechanism used to install the operator
	// (manifest, helm, olm)
	Method string `json:"method,omitempty"`

	// BarmanPluginVersion is the requested plugin-barman-cloud version
	BarmanPluginVersion string `json:"barmanPluginVersion,omitempty"`

	// BarmanPluginVersionResolved is the plugin-barman-cloud version that
	// has actually been installed
	BarmanPluginVersionResolved string `json:"barmanPluginVersionResolved,omitempty"`
}

// RegistryPullSecretConfiguration holds the credentials of a private
// container registry
type RegistryPullSecretConfiguration struct {
	Server   string `json:"server,omitempty"`
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
}

// AzureConfiguration configures the Azure Blob Storage backend used by the
// azure-blob backup tests
type AzureConfiguration struct {
	StorageAccount string `json:"storageAccount,omitempty"`
	StorageKey     string `json:"storageKey,omitempty"`
	BlobContainer  string `json:"blobContainer,omitempty"`
}

// MajorUpgradeConfiguration overrides the images used by the major upgrade
// tests, allowing them to run against images built from PostgreSQL trunk
type MajorUpgradeConfiguration struct {
	// ImageRegistry is the registry the major upgrade target images are
	// pulled from. When empty, the official images are used.
	ImageRegistry string `json:"imageRegistry,omitempty"`

	// StandardSuffix is the tag suffix of the standard image flavor
	StandardSuffix string `json:"standardSuffix,omitempty"`

	// MinimalSuffix is the tag suffix of the minimal image flavor
	MinimalSuffix string `json:"minimalSuffix,omitempty"`

	// SystemSuffix is the tag suffix of the system image flavor
	SystemSuffix string `json:"systemSuffix,omitempty"`

	// PostGISSuffix is the tag suffix of the PostGIS image flavor
	PostGISSuffix string `json:"postgisSuffix,omitempty"`

	// SkipArchiveScenario skips the WAL archiving scenario of the major
	// upgrade tests
	SkipArchiveScenario bool `json:"skipArchiveScenario,omitempty"`
}

var (
	currentMu sync.Mutex
	current   *Config
)

// Load reads and parses the configuration file at path. Unknown fields are
// rejected.
func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path) // #nosec G304 -- path is chosen by the test runner
	if err != nil {
		return nil, fmt.Errorf("reading the e2e configuration file: %w", err)
	}

	var cfg Config
	if err := yaml.UnmarshalStrict(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing the e2e configuration file %q: %w", path, err)
	}

	cfg.setDefaults()
	return &cfg, nil
}

// NewDefault returns a configuration with every field at its default value,
// equivalent to loading an empty file
func NewDefault() *Config {
	cfg := &Config{}
	cfg.setDefaults()
	return cfg
}

func (c *Config) setDefaults() {
	if c.Postgres.Image == "" {
		c.Postgres.Image = versions.DefaultImageName
	}
	if c.Postgres.ImageRepository == "" {
		c.Postgres.ImageRepository = "ghcr.io/cloudnative-pg/postgresql"
	}
	if c.Postgres.PostGISImageRepository == "" {
		c.Postgres.PostGISImageRepository = "ghcr.io/cloudnative-pg/postgis"
	}
	if c.CloudVendor == "" {
		c.CloudVendor = VendorKind
	}
}

// Set installs cfg as the configuration returned by Current
func Set(cfg *Config) {
	currentMu.Lock()
	defer currentMu.Unlock()
	current = cfg
}

// Current returns the configuration of the run. If none has been loaded,
// it returns the default configuration.
func Current() *Config {
	currentMu.Lock()
	defer currentMu.Unlock()
	if current == nil {
		current = NewDefault()
	}
	return current
}
