#!/usr/bin/env bash

##
## Copyright © contributors to CloudNativePG, established as
## CloudNativePG a Series of LF Projects, LLC.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## SPDX-License-Identifier: Apache-2.0
##

# This file is meant to be sourced. It defines generate_e2e_config, which
# renders the configuration file driving the e2e suite (tests/config) from
# the variables currently set in the shell. The suite reads no environment
# variables: this file is the only channel between the scripts and the
# suite.

# yaml_string prints its argument as a YAML double-quoted scalar
yaml_string() {
  local value=$1
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  printf '"%s"' "${value}"
}

# generate_e2e_config writes the e2e configuration file.
#
# Usage: generate_e2e_config <skipUpgradeSuite: true|false>
#
# The file is written to E2E_CONFIG_PATH, defaulting to
# tests/e2e/config.yaml, which is where the suite looks for it. It may
# contain credentials, so it is not world-readable and must stay out of
# directories uploaded as CI artifacts.
generate_e2e_config() {
  local skip_upgrade_suite=$1
  local config_path="${E2E_CONFIG_PATH:-${ROOT_DIR}/tests/e2e/config.yaml}"

  local label_filter=""
  if [ -n "${FEATURE_TYPE:-}" ]; then
    label_filter="${FEATURE_TYPE//,/ || }"
  fi

  rm -f "${config_path}"
  touch "${config_path}"
  chmod 600 "${config_path}"

  {
    echo "# Generated by hack/e2e scripts from the invocation environment."
    echo "postgres:"
    echo "  image: $(yaml_string "${POSTGRES_IMG}")"
    if [ -n "${E2E_PRE_ROLLING_UPDATE_IMG:-}" ]; then
      echo "  preRollingUpdateImage: $(yaml_string "${E2E_PRE_ROLLING_UPDATE_IMG}")"
    fi
    if [ -n "${POSTGRES_IMG_REPOSITORY:-}" ]; then
      echo "  imageRepository: $(yaml_string "${POSTGRES_IMG_REPOSITORY}")"
    fi
    if [ -n "${POSTGIS_IMG_REPOSITORY:-}" ]; then
      echo "  postgisImageRepository: $(yaml_string "${POSTGIS_IMG_REPOSITORY}")"
    fi

    if [ -n "${E2E_DEFAULT_STORAGE_CLASS:-}${E2E_CSI_STORAGE_CLASS:-}${E2E_DEFAULT_VOLUMESNAPSHOT_CLASS:-}" ]; then
      echo "storage:"
      if [ -n "${E2E_DEFAULT_STORAGE_CLASS:-}" ]; then
        echo "  storageClass: $(yaml_string "${E2E_DEFAULT_STORAGE_CLASS}")"
      fi
      if [ -n "${E2E_CSI_STORAGE_CLASS:-}" ]; then
        echo "  csiStorageClass: $(yaml_string "${E2E_CSI_STORAGE_CLASS}")"
      fi
      if [ -n "${E2E_DEFAULT_VOLUMESNAPSHOT_CLASS:-}" ]; then
        echo "  volumeSnapshotClass: $(yaml_string "${E2E_DEFAULT_VOLUMESNAPSHOT_CLASS}")"
      fi
    fi

    if [ -n "${TEST_CLOUD_VENDOR:-}" ]; then
      echo "cloudVendor: $(yaml_string "${TEST_CLOUD_VENDOR}")"
    fi
    if [ -n "${TEST_DEPTH:-}" ]; then
      echo "depth: ${TEST_DEPTH}"
    fi
    if [ -n "${label_filter}" ]; then
      echo "labelFilter: $(yaml_string "${label_filter}")"
    fi
    echo "skipUpgradeSuite: ${skip_upgrade_suite}"
    if [ -n "${TEST_TIMEOUTS:-}" ]; then
      # TEST_TIMEOUTS is a JSON object, which is valid YAML
      echo "timeouts: ${TEST_TIMEOUTS}"
    fi

    echo "deployment:"
    echo "  method: $(yaml_string "${CNPG_DEPLOYMENT_METHOD:-manifest}")"
    if [ -n "${BARMAN_PLUGIN_VERSION:-}" ]; then
      echo "  barmanPluginVersion: $(yaml_string "${BARMAN_PLUGIN_VERSION}")"
    fi
    if [ -n "${BARMAN_PLUGIN_VERSION_RESOLVED:-}" ]; then
      echo "  barmanPluginVersionResolved: $(yaml_string "${BARMAN_PLUGIN_VERSION_RESOLVED}")"
    fi

    if [ -n "${DOCKER_SERVER:-}${DOCKER_USERNAME:-}${DOCKER_PASSWORD:-}" ]; then
      echo "registryPullSecret:"
      echo "  server: $(yaml_string "${DOCKER_SERVER:-}")"
      echo "  username: $(yaml_string "${DOCKER_USERNAME:-}")"
      echo "  password: $(yaml_string "${DOCKER_PASSWORD:-}")"
    fi

    if [ -n "${AZURE_STORAGE_ACCOUNT:-}${AZURE_STORAGE_KEY:-}${AZURE_BLOB_CONTAINER:-}" ]; then
      echo "azure:"
      echo "  storageAccount: $(yaml_string "${AZURE_STORAGE_ACCOUNT:-}")"
      echo "  storageKey: $(yaml_string "${AZURE_STORAGE_KEY:-}")"
      echo "  blobContainer: $(yaml_string "${AZURE_BLOB_CONTAINER:-}")"
    fi

    if [ -n "${PRESERVE_NAMESPACES:-}" ]; then
      echo "preserveNamespaces:"
      for namespace in ${PRESERVE_NAMESPACES}; do
        echo "  - $(yaml_string "${namespace}")"
      done
    fi

    if [ -n "${BRANCH_NAME:-}" ]; then
      echo "branchName: $(yaml_string "${BRANCH_NAME}")"
    fi

    if [ -n "${POSTGRES_MAJOR_UPGRADE_IMAGE_REGISTRY:-}" ]; then
      echo "majorUpgrade:"
      echo "  imageRegistry: $(yaml_string "${POSTGRES_MAJOR_UPGRADE_IMAGE_REGISTRY}")"
      if [ -n "${POSTGRES_MAJOR_UPGRADE_STANDARD_SUFFIX:-}" ]; then
        echo "  standardSuffix: $(yaml_string "${POSTGRES_MAJOR_UPGRADE_STANDARD_SUFFIX}")"
      fi
      if [ -n "${POSTGRES_MAJOR_UPGRADE_MINIMAL_SUFFIX:-}" ]; then
        echo "  minimalSuffix: $(yaml_string "${POSTGRES_MAJOR_UPGRADE_MINIMAL_SUFFIX}")"
      fi
      if [ -n "${POSTGRES_MAJOR_UPGRADE_SYSTEM_SUFFIX:-}" ]; then
        echo "  systemSuffix: $(yaml_string "${POSTGRES_MAJOR_UPGRADE_SYSTEM_SUFFIX}")"
      fi
      if [ -n "${POSTGRES_MAJOR_UPGRADE_POSTGIS_SUFFIX:-}" ]; then
        echo "  postgisSuffix: $(yaml_string "${POSTGRES_MAJOR_UPGRADE_POSTGIS_SUFFIX}")"
      fi
      if [ -n "${POSTGRES_MAJOR_UPGRADE_SKIP_ARCHIVE_SCENARIO:-}" ]; then
        echo "  skipArchiveScenario: true"
      fi
    elif [ -n "${POSTGRES_MAJOR_UPGRADE_SKIP_ARCHIVE_SCENARIO:-}" ]; then
      echo "majorUpgrade:"
      echo "  skipArchiveScenario: true"
    fi
  } >> "${config_path}"

  echo "e2e configuration written to ${config_path}"
}
