hiddenMemberFields:
  - "TypeMeta"

externalPackages:
  - match: ^k8s\.io/apimachinery/pkg/apis/meta/v1\.Duration$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#Duration
  - match: ^k8s\.io/apimachinery/pkg/apis/meta/v1\.GroupVersionKind$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#GroupVersionKind
  - match: ^k8s\.io/apimachinery/pkg/apis/meta/v1\.GroupVersionResource$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#GroupVersionResource
  - match: ^k8s\.io/apimachinery/pkg/types\.UID$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/types#UID
  - match: ^k8s\.io/apimachinery/pkg/runtime\.RawExtension$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime/#RawExtension
  - match: ^k8s\.io/apimachinery/pkg/api/resource\.QuantityValue$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#QuantityValue
  - match: ^k8s\.io/apimachinery/pkg/runtime\.Unknown$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime#Unknown
  - match: ^time\.Duration$
    target: https://pkg.go.dev/time#Duration
  - match: ^k8s\.io/(api|apimachinery/pkg/apis)/
    target: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#{{- lower .TypeIdentifier -}}-{{- arrIndex .PackageSegments -1 -}}-{{- arrIndex .PackageSegments -2 -}}

hideTypePatterns:
  - "ParseError$"
  - "List$"

markdownDisabled: false

stripPrefix:
  - k8s.io/api/
  - k8s.io/apimachinery/pkg/apis/

apis:
  - name: cloudnative-pg
    title: API Reference
    package: github.com/cloudnative-pg/cloudnative-pg
    path: api/v1
