hiddenMemberFields:
  - "TypeMeta"

externalPackages:
  - match: ^github\.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1\.RelabelConfig$
    target: https://pkg.go.dev/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1#RelabelConfig
  - match: ^k8s\.io/apimachinery/pkg/apis/meta/v1\.Duration$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#Duration
  - match: ^k8s\.io/apimachinery/pkg/apis/meta/v1\.GroupVersionKind$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#GroupVersionKind
  - match: ^k8s\.io/apimachinery/pkg/apis/meta/v1\.GroupVersionResource$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#GroupVersionResource
  - match: ^k8s\.io/apimachinery/pkg/types\.UID$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/types#UID
  - match: ^k8s\.io/apimachinery/pkg/runtime\.RawExtension$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime/#RawExtension
  - match: ^k8s\.io/apimachinery/pkg/api/resource\.Quantity$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#Quantity
  - match: ^k8s\.io/apimachinery/pkg/api/resource\.QuantityValue$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#QuantityValue
  - match: ^k8s\.io/apimachinery/pkg/runtime\.Unknown$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime#Unknown
  - match: ^time\.Duration$
    target: https://pkg.go.dev/time#Duration
  - match: ^k8s\.io/(api|apimachinery/pkg/apis)/
    target: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#{{- lower .TypeIdentifier -}}-{{- arrIndex .PackageSegments -1 -}}-{{- arrIndex .PackageSegments -2 -}}
  - match: ^github\.com/cloudnative-pg/machinery
    target: https://pkg.go.dev/github.com/cloudnative-pg/machinery/pkg/api/#{{- .TypeIdentifier }}
  - match: ^github\.com/cloudnative-pg/barman-cloud
    target: https://pkg.go.dev/github.com/cloudnative-pg/barman-cloud/pkg/api/#{{- .TypeIdentifier }}

hideTypePatterns:
  - "ParseError$"
  - "List$"

markdownDisabled: false

stripPrefix:
  - k8s.io/api/
  - k8s.io/apimachinery/pkg/apis/

apis:
  - name: cloudnative-pg
    title: API Reference
    package: github.com/cloudnative-pg/cloudnative-pg
    path: api/v1
