# This workflow adds support for custom "slash commands" in the CI/CD pipeline.
# It is triggered by comments made on pull requests.
#
# 1. If the comment starts with "/ok-to-merge", it will label the PR with
#    "ok to merge :ok_hand:"
#
name: slash-command
on:
  issue_comment:
    types: [created]

jobs:
  ok-to-merge:
    if: |
        github.event.issue.pull_request &&
        startsWith(github.event.comment.body, '/ok-to-merge')
    runs-on: ubuntu-22.04
    steps:
      - name: Check User Permission
        id: checkUser
        uses: actions-cool/check-user-permission@v2
        with:
          require: 'write'
      - name: Add "ok to merge :ok_hand:" label to CNPG PR
        uses: actions-ecosystem/action-add-labels@v1.1.3
        if: steps.checkUser.outputs.require-result == 'true'
        with:
          github_token: ${{ secrets.REPO_GHA_PAT }}
          labels: "ok to merge :ok_hand:"
