# This workflow will inspect a pull request to ensure there is a linked issue or a
# valid issue is mentioned in the body. If neither is present it fails the check and adds
# a comment alerting users of this missing requirement.
name: VerifyIssue

on:
  pull_request:
    branches-ignore:
      - 'renovate/**'
    types:
    - edited
    - synchronize
    - opened
    - reopened
    - labeled
    - unlabeled

permissions: read-all

jobs:
  verify_linked_issue:
    runs-on: ubuntu-latest
    name: Ensure Pull Request has a linked issue.
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-issue') }}
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@2d8e2e47a462cc7b07ba5e6cab6f9d57bd36672e # v1.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
