# This workflow will inspect a pull request to ensure there is a linked issue or a
# valid issue is mentioned in the body. If neither is present it fails the check and adds
# a comment alerting users of this missing requirement.
name: VerifyIssue

on:
  pull_request:
    branches-ignore:
      - 'renovate/**'
    types:
    - edited
    - synchronize
    - opened
    - reopened
    - labeled
    - unlabeled

permissions: read-all

jobs:
  verify_linked_issue:
    runs-on: ubuntu-latest
    name: Ensure Pull Request has a linked issue.
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-issue') }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Verify Linked Issue
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            const body = context.payload.pull_request.body || '';
            core.debug(`Checking PR body: "${body}"`);

            const matches = [...body.matchAll(/#(\d+)/g)];
            for (const m of matches) {
              const issueNumber = parseInt(m[1], 10);
              try {
                await github.rest.issues.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                });
                core.notice(`Success! Linked issue #${issueNumber} found in body.`);
                return;
              } catch {
                core.debug(`#${issueNumber} is not a valid issue.`);
              }
            }

            const message =
              'Build Error! No Linked Issue found. Please link an issue or mention it in the body using #<issue_id>';
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message,
            });
            core.setFailed('No Linked Issue Found!');
