name: Sync Docs

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - 'docs/src/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Tag (e.g., "v1.28.0") or "main"'
        required: true
        default: 'main'

permissions: {}

jobs:
  dispatch-tag:
    if: >-
      github.repository_owner == 'cloudnative-pg' &&
      startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Docs Repository Workflow
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4
        with:
          repository: cloudnative-pg/docs
          token: ${{ secrets.REPO_GHA_PAT }}
          event-type: cnpg-docs-release
          client-payload: ${{ format('{{"tag":{0}}}', toJSON(github.ref_name)) }}

  dispatch-main:
    if: >-
      github.repository_owner == 'cloudnative-pg' &&
      !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Docs Repository Workflow
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4
        with:
          repository: cloudnative-pg/docs
          token: ${{ secrets.REPO_GHA_PAT }}
          event-type: cnpg-docs-release
          client-payload: '{"tag":"main"}'

  dispatch-manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Docs Repository Workflow
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4
        with:
          repository: cloudnative-pg/docs
          token: ${{ secrets.REPO_GHA_PAT }}
          event-type: cnpg-docs-release
          client-payload: ${{ format('{{"tag":{0}}}', toJSON(github.event.inputs.version)) }}
