name: unit-tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  GOLANG_VERSION: "1.13.x"
  GOLANGCI_LINT_VERSION: "v1.33"
  KUBEBUILDER_VERSION: "2.3.1"

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:

  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  tests:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      # Install kubebuilder that is a requirement to run tests
      - name: Install Kubebuilder
        run: |
          mkdir -p /tmp/kubebuilder
          curl -sSL https://go.kubebuilder.io/dl/${{ env.KUBEBUILDER_VERSION }}/$(go env GOOS)/$(go env GOARCH) | tar --strip-components=1 -xz -C /tmp/kubebuilder
          sudo mv /tmp/kubebuilder /usr/local/
      - name: Run unit tests
        run:
          make test

  dispatch:
    name: Trigger E2E tests workflows
    needs:
      - golangci
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch trigger-e2e event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-e2e
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
